export type LangCode =
  | "en" | "ig" | "ha" | "yo"
  | "fr" | "zh" | "ar" | "es" | "pt" | "de" | "sw";

export interface LangMeta {
  code: LangCode;
  label: string;
  native: string;
  flag: string;
  rtl?: boolean;
}

export const languages: LangMeta[] = [
  { code: "en", label: "English",    native: "English",    flag: "🇬🇧" },
  { code: "ig", label: "Igbo",       native: "Igbo",       flag: "🇳🇬" },
  { code: "ha", label: "Hausa",      native: "Hausa",      flag: "🇳🇬" },
  { code: "yo", label: "Yoruba",     native: "Yorùbá",     flag: "🇳🇬" },
  { code: "fr", label: "French",     native: "Français",   flag: "🇫🇷" },
  { code: "zh", label: "Chinese",    native: "中文",        flag: "🇨🇳" },
  { code: "ar", label: "Arabic",     native: "العربية",    flag: "🇸🇦", rtl: true },
  { code: "es", label: "Spanish",    native: "Español",    flag: "🇪🇸" },
  { code: "pt", label: "Portuguese", native: "Português",  flag: "🇧🇷" },
  { code: "de", label: "German",     native: "Deutsch",    flag: "🇩🇪" },
  { code: "sw", label: "Swahili",    native: "Kiswahili",  flag: "🇰🇪" },
];

export interface Translations {
  nav: {
    home: string; about: string; services: string; projects: string;
    properties: string; careers: string; contact: string; getQuote: string; team: string;
  };
  common: {
    learnMore: string; contactUs: string; viewAll: string; startProject: string;
    getQuote: string; viewProjects: string; readMore: string; submit: string;
    calculate: string; reset: string; search: string; filters: string;
    bookInspection: string; applyNow: string; sendMessage: string;
    allRightsReserved: string; buildingCities: string; privacyPolicy: string;
    termsOfService: string; emergencyLine: string;
    ourDivisions: string; quickLinks: string;
  };
  home: {
    heroBadge: string; heroH1a: string; heroH1b: string; heroH1c: string;
    heroSubtitle: string; heroFindProperty: string;
    statProjects: string; statWorkforce: string; statClients: string; statProperties: string;
    servicesBadge: string; servicesTitle1: string; servicesTitle2: string; servicesSubtitle: string;
    whyBadge: string; whyTitle1: string; whyTitle2: string; whyBody: string;
    portfolioBadge: string; portfolioTitle: string; featuredProjects: string;
    testimonialsBadge: string; testimonialsTitle: string;
    ctaTitle1: string; ctaTitle2: string; ctaSubtitle: string; ctaAbout: string;
    trustedBy: string;
  };
  about: {
    heroBadge: string; heroTitle1: string; heroTitle2: string; heroSubtitle: string;
    missionLabel: string; visionLabel: string;
    valuesBadge: string; valuesTitle1: string; valuesTitle2: string;
    certBadge: string; certTitle1: string; certTitle2: string; certSubtitle: string;
    workforceBadge: string; workforceTitle1: string; workforceTitle2: string;
    timelineBadge: string; timelineTitle1: string; timelineTitle2: string;
    leadershipBadge: string; leadershipTitle: string;
    ctaTitle1: string; ctaTitle2: string; ctaSubtitle: string;
  };
  services: {
    heroBadge: string; heroTitle1: string; heroTitle2: string; heroSubtitle: string;
    divisionLabel: string; ctaTitle1: string; ctaTitle2: string; ctaSubtitle: string;
    divisionNames: string[];
  };
  projects: {
    heroBadge: string; heroTitle1: string; heroTitle2: string; heroSubtitle: string;
    filterAll: string; enquire: string;
    ctaTitle1: string; ctaTitle2: string; ctaSubtitle: string; startProject: string;
    statValue: string; statContract: string; statStates: string; statDelivery: string;
  };
  properties: {
    heroBadge: string; heroTitle1: string; heroTitle2: string; heroSubtitle: string;
    searchPlaceholder: string; sortNewest: string; sortLowHigh: string; sortHighLow: string;
    listingsAvailable: string; saved: string;
    bookInspection: string; confirmBooking: string;
    whyBadge: string; whyTitle1: string; whyTitle2: string;
    propFor: string; beds: string; baths: string;
    popular: string;
  };
  careers: {
    heroBadge: string; heroTitle1: string; heroTitle2: string; heroSubtitle: string;
    openRolesBadge: string; openRolesTitle: string;
    artisanBadge: string; artisanTitle1: string; artisanTitle2: string; artisanSubtitle: string;
    formBadge: string; formTitle: string;
    tabJob: string; tabLabor: string; tabContractor: string;
    submitApplication: string;
  };
  contact: {
    heroBadge: string; heroTitle1: string; heroTitle2: string; heroSubtitle: string;
    sendMessage: string; messageSent: string; thankYou: string; sendAnother: string;
    fullName: string; emailAddress: string; phoneNumber: string;
    serviceRequired: string; estimatedBudget: string; projectDescription: string;
    projectDescPlaceholder: string;
    directContacts: string; responseTime: string;
    generalEnquiries: string; projectQuotations: string; emergencySupport: string;
    siteEmergency: string; siteEmergencyDesc: string;
    officesBadge: string; officesTitle1: string; officesTitle2: string;
  };
  footer: {
    tagline: string;
  };
}

const t: Record<LangCode, Translations> = {
  /* ═══════════════ ENGLISH ═══════════════ */
  en: {
    nav: { home: "Home", about: "About", services: "Services", projects: "Projects", properties: "Properties", careers: "Careers", team: "Our Team", contact: "Contact", getQuote: "Get a Quote" },
    common: { learnMore: "Learn More", contactUs: "Contact Us", viewAll: "View All", startProject: "Start Your Project", getQuote: "Get a Quote", viewProjects: "View Our Projects", readMore: "Read More", submit: "Submit", calculate: "Calculate Estimate", reset: "Reset", search: "Search", filters: "Filters", bookInspection: "Book Inspection", applyNow: "Apply Now", sendMessage: "Send Message", allRightsReserved: "All rights reserved.", buildingCities: "Building Cities. Creating Futures.", privacyPolicy: "Privacy Policy", termsOfService: "Terms of Service", emergencyLine: "Emergency Line", ourDivisions: "Our Divisions", quickLinks: "Quick Links" },
    home: { heroBadge: "Building Cities. Creating Futures.", heroH1a: "Africa's Premier", heroH1b: "Construction", heroH1c: "Powerhouse", heroSubtitle: "FCC Fore-City Construction delivers world-class construction, real estate, and integrated property solutions — from foundation to finish, across Africa's fastest-growing cities.", heroFindProperty: "Find a Property", statProjects: "Projects Completed", statWorkforce: "Skilled Workforce", statClients: "Happy Clients", statProperties: "Properties Delivered", servicesBadge: "What We Do", servicesTitle1: "Five Powerful Divisions.", servicesTitle2: "One Company.", servicesSubtitle: "From breaking ground to handing over keys, we deliver end-to-end built-environment solutions under one roof.", whyBadge: "Why Choose FCC", whyTitle1: "Trusted by Nigeria's", whyTitle2: "Biggest Brands", whyBody: "In 15+ years, we've built a legacy of trust, quality, and on-time delivery. Our integrated approach means fewer contractors, faster completion, and better outcomes.", portfolioBadge: "Portfolio", portfolioTitle: "Featured Projects", featuredProjects: "All Projects", testimonialsBadge: "Testimonials", testimonialsTitle: "What Our Clients Say", ctaTitle1: "Ready to Build", ctaTitle2: "Something Extraordinary?", ctaSubtitle: "From your first consultation to project handover, FCC is with you every step of the way.", ctaAbout: "About FCC", trustedBy: "Trusted by Industry Leaders" },
    about: { heroBadge: "Our Story", heroTitle1: "Building Africa,", heroTitle2: "One Project at a Time", heroSubtitle: "FCC Fore-City Construction is Nigeria's most integrated built-environment company — delivering construction, real estate, property management, interior design, and workforce solutions under one powerful brand.", missionLabel: "Our Mission", visionLabel: "Our Vision", valuesBadge: "Our Values", valuesTitle1: "What Drives Us", valuesTitle2: "Every Single Day", certBadge: "Accreditations", certTitle1: "Certified &", certTitle2: "Internationally Accredited", certSubtitle: "Our certifications are not just badges — they are proof of our commitment to international quality and safety standards.", workforceBadge: "Our Workforce", workforceTitle1: "1,000+ Professionals.", workforceTitle2: "One Unstoppable Team.", timelineBadge: "Our Journey", timelineTitle1: "15 Years of", timelineTitle2: "Building Excellence", leadershipBadge: "Leadership", leadershipTitle: "Meet the Team", ctaTitle1: "Let's Build Something", ctaTitle2: "Great Together", ctaSubtitle: "Whether you're starting a new project or looking to invest in real estate, FCC is ready." },
    services: { heroBadge: "Our Services", heroTitle1: "Five Divisions.", heroTitle2: "Unlimited Possibilities.", heroSubtitle: "From breaking ground to property management, FCC covers every stage of the built-environment cycle under one integrated, expert-led brand.", divisionLabel: "Division", ctaTitle1: "Need a Custom", ctaTitle2: "Service Package?", ctaSubtitle: "We tailor our services to your specific project requirements and budget. Talk to our team today.", divisionNames: ["Construction & Engineering", "Real Estate & Property", "Facility & Property Management", "Interior & Finishing", "Workforce & Equipment Solutions"] },
    projects: { heroBadge: "Our Portfolio", heroTitle1: "500+ Projects.", heroTitle2: "Zero Compromises.", heroSubtitle: "From residential estates to national infrastructure — every project in our portfolio represents a commitment to excellence, innovation, and on-time delivery.", filterAll: "All", enquire: "Enquire", ctaTitle1: "Your Project Could Be", ctaTitle2: "Our Next Masterpiece", ctaSubtitle: "Let's discuss your vision and turn it into an award-winning project.", startProject: "Start a Project", statValue: "Total Contract Value", statContract: "Projects Completed", statStates: "States Covered", statDelivery: "On-Time Delivery Rate" },
    properties: { heroBadge: "Property Marketplace", heroTitle1: "Find Your", heroTitle2: "Perfect Property", heroSubtitle: "Buy, rent, or invest in premium properties across Nigeria's fastest-growing cities — verified listings, trusted agents, seamless transactions.", searchPlaceholder: "Search location, estate, or property type...", sortNewest: "Sort: Newest", sortLowHigh: "Price: Low to High", sortHighLow: "Price: High to Low", listingsAvailable: "Listings Available", saved: "saved", bookInspection: "Book Inspection", confirmBooking: "Confirm Inspection Booking", whyBadge: "Why FCC Properties", whyTitle1: "The Safest Way to Buy", whyTitle2: "Property in Nigeria", propFor: "For", beds: "Bed", baths: "Bath", popular: "Popular" },
    careers: { heroBadge: "Join Our Team", heroTitle1: "Build Your Career.", heroTitle2: "Build Africa's Future.", heroSubtitle: "Join a team of 1,000+ professionals shaping Africa's built environment. FCC offers career growth, competitive compensation, and the opportunity to work on landmark projects.", openRolesBadge: "Open Roles", openRolesTitle: "Current Opportunities", artisanBadge: "Artisan Database", artisanTitle1: "Are You a Skilled", artisanTitle2: "Trade Professional?", artisanSubtitle: "Join Nigeria's premier construction workforce database. Get matched with projects, earn more, and build your career.", formBadge: "Apply Now", formTitle: "Submit Your Application", tabJob: "Job Application", tabLabor: "Labor Registration", tabContractor: "Contractor Signup", submitApplication: "Submit Application" },
    contact: { heroBadge: "Get in Touch", heroTitle1: "Let's Build", heroTitle2: "Your Vision Together", heroSubtitle: "Ready to start a project? Looking for an investment property? Need a workforce solution? Our team is ready to respond within 24 hours.", sendMessage: "Send Us a Message", messageSent: "Message Sent!", thankYou: "Thank you for reaching out. Our team will respond within 24 hours.", sendAnother: "Send Another Message", fullName: "Full Name", emailAddress: "Email Address", phoneNumber: "Phone Number", serviceRequired: "Service Required", estimatedBudget: "Estimated Budget", projectDescription: "Project Description", projectDescPlaceholder: "Tell us about your project, timeline, location, and any specific requirements...", directContacts: "Direct Contacts", responseTime: "Response Times", generalEnquiries: "General Enquiries", projectQuotations: "Project Quotations", emergencySupport: "Emergency Site Support", siteEmergency: "Site Emergency?", siteEmergencyDesc: "Call our 24/7 emergency line for urgent site issues.", officesBadge: "Our Offices", officesTitle1: "Find Us", officesTitle2: "Across Nigeria" },
    footer: { tagline: "One company. Endless possibilities. Building cities and creating futures across Africa." },
  },

  /* ═══════════════ IGBO ═══════════════ */
  ig: {
    nav: { home: "Ụlọ", about: "Maka Anyị", services: "Ọrụ Anyị", projects: "Ọrụ Mmepụta", properties: "Ụlọ Ahịa", careers: "Ọrụ", team: "Òtù Anyị", contact: "Kpọtụrụ Anyị", getQuote: "Nweta Ọnụahịa" },
    common: { learnMore: "Mụtakwuo", contactUs: "Kpọtụrụ Anyị", viewAll: "Hụ Niile", startProject: "Malite Ọrụ Gị", getQuote: "Nweta Ọnụahịa", viewProjects: "Hụ Ọrụ Anyị", readMore: "Gụọ Ọzọ", submit: "Zipu", calculate: "Gbakọọ Ọnụ Ego", reset: "Malite Ọzọ", search: "Chọọ", filters: "Àtụ", bookInspection: "Depụta Nlele", applyNow: "Tinye Akwụkwọ", sendMessage: "Zipu Ozi", allRightsReserved: "Ikike niile echekwara.", buildingCities: "Ịwu Obodo. Ịmepụta Ọdịnihu.", privacyPolicy: "Iwu Nzuzo", termsOfService: "Ọnọdụ Ọrụ", emergencyLine: "Akara Ihe Mberede", ourDivisions: "Ngalaba Anyị", quickLinks: "Njikọ Ngwa Ngwa" },
    home: { heroBadge: "Ịwu Obodo. Ịmepụta Ọdịnihu.", heroH1a: "Ụlọ Ọrụ Kachasị Mma", heroH1b: "Nwu Ụlọ", heroH1c: "n'Afrịka", heroSubtitle: "FCC Fore-City Construction na-eweta ọrụ nwu ụlọ, ala ahịa, na ngwọta ụlọ nke ụwa — site n'ntọala ruo njedebe, n'obodo ndị na-eto eto nke Afrịka.", heroFindProperty: "Chọọ Ụlọ", statProjects: "Ọrụ Emechara", statWorkforce: "Ndị Ọrụ Nkà", statClients: "Ndị Ọrụ Ewesara Obi", statProperties: "Ụlọ Nyefedoro", servicesBadge: "Ihe Anyị Na-arụ", servicesTitle1: "Ngalaba Ise Siri Ike.", servicesTitle2: "Otu Ụlọ Ọrụ.", servicesSubtitle: "Site n'ịmalite ihe ruo n'inyefe igodo, anyị na-enye ngwọta gburugburu ụlọ n'okpuru otu ụlọ.", whyBadge: "Gịnị Kpatara Ịhọrọ FCC", whyTitle1: "Ndị Nigeria Tụkwasara", whyTitle2: "Obi Na-ahụ FCC n'Anya", whyBody: "N'ime afọ 15+, anyị ewulitela aha nke ntụkwasị obi, àgwà mma, na nnyefe n'oge. Ụzọ anyị zikotara pụtara ndị ọrụ ole na ole, nwụchara ngwa, na nsonaazụ dị mma.", portfolioBadge: "Ihe Anyị Rụrụ", portfolioTitle: "Ọrụ Mmepụta Ama Ama", featuredProjects: "Ọrụ Niile", testimonialsBadge: "Asụsụ Ndị Ọrụ", testimonialsTitle: "Ihe Ndị Ọrụ Anyị Kwuru", ctaTitle1: "Ị Dị Njikere Iwu", ctaTitle2: "Ihe Pụtara Ìhè?", ctaSubtitle: "Site n'ọgbako mbụ gị ruo n'inyefe ọrụ, FCC nọ ebe ị nọ n'oge ọ bụla.", ctaAbout: "Maka FCC", trustedBy: "Ndị Isi Ụlọ Ọrụ Tụkwasara Obi" },
    about: { heroBadge: "Akụkọ Anyị", heroTitle1: "Ịwu Afrịka,", heroTitle2: "Otu Ọrụ n'Oge Ọ Bụla", heroSubtitle: "FCC bụ ụlọ ọrụ nwu ụlọ kachasị jikọtara ọnụ na Nigeria — na-enye ọrụ nwu ụlọ, ala ahịa, njikwa ụlọ, nhazi ime ụlọ, na ngwọta ndị ọrụ.", missionLabel: "Ebumnobi Anyị", visionLabel: "Ọhụụ Anyị", valuesBadge: "Ụkpụrụ Anyị", valuesTitle1: "Ihe Na-akpali Anyị", valuesTitle2: "N'Ụbọchị Ọ Bụla", certBadge: "Asambodo", certTitle1: "Akwado &", certTitle2: "Akwadoro n'Ụwa Niile", certSubtitle: "Asambodo anyị abụghị naanị ihe mgbakwunye — ha bụ ihe akaebe nke ịkwupụta isi anyị na àgwà mma na nchekwa.", workforceBadge: "Ndị Ọrụ Anyị", workforceTitle1: "Ọkachamara 1,000+.", workforceTitle2: "Otu Ndị Ọrụ Ike.", timelineBadge: "Njem Anyị", timelineTitle1: "Afọ 15 nke", timelineTitle2: "Ịwu Ọkachamanwa", leadershipBadge: "Ndị Ọchịchị", leadershipTitle: "Zụọ Ndị Ọrụ Anyị", ctaTitle1: "Ka Anyị Wuo", ctaTitle2: "Ihe Dị Mma Ọnụ", ctaSubtitle: "Ma ị malitere ọrụ ọhụrụ ma ọ bụ ị chọọ ịtinye ego na ụlọ ahịa, FCC dị njikere." },
    services: { heroBadge: "Ọrụ Anyị", heroTitle1: "Ngalaba Ise.", heroTitle2: "Ohere Enweghị Njedebe.", heroSubtitle: "Site n'ịmalite ruo njikwa ụlọ, FCC na-ekpuchie ọ bụla ọkwa nke gburugburu ụlọ n'okpuru otu akara.", divisionLabel: "Ngalaba", ctaTitle1: "Ị Chọọ Ịhaziri", ctaTitle2: "Ngọngọ Ọrụ?", ctaSubtitle: "Anyị na-ahaziri ọrụ anyị dị ka ihe ọrụ gị chọọ na ego gị. Kpọọ ndị ọrụ anyị taa.", divisionNames: ["Nwu Ụlọ & Injinia", "Ụlọ Ahịa & Ala", "Njikwa Ụlọ & Ala", "Ime Ụlọ & Wykończenie", "Ndị Ọrụ & Ngwa"] },
    projects: { heroBadge: "Ihe Anyị Rụrụ", heroTitle1: "Ọrụ 500+.", heroTitle2: "Enweghị Mkpọsa.", heroSubtitle: "Site n'oge obodo na ihe omume nke ọchịchị — ọrụ ọ bụla n'ime ihe anyị rụrụ na-ọchị nkwupụta nkwanye ọkachamanwa, ihe ọhụrụ, na nnyefe n'oge.", filterAll: "Niile", enquire: "Jụọ Ajụjụ", ctaTitle1: "Ọrụ Gị Nwere Ike Bụrụ", ctaTitle2: "Ihe Anyị Ga-emepụta Ọzọ", ctaSubtitle: "Ka anyị kwurịta ọhụụ gị ma ghọọ ya ọrụ siri ike.", startProject: "Malite Ọrụ", statValue: "Ọnụ Ego Ụmụ Ọrụ Niile", statContract: "Ọrụ Emechara", statStates: "Steeti Anyị Rụchara Ọrụ", statDelivery: "Ọsọ Nnyefe n'Oge" },
    properties: { heroBadge: "Ọchịchọ Ụlọ", heroTitle1: "Chọọ Ụlọ", heroTitle2: "Ziri Ezi Gị", heroSubtitle: "Zụọ, mee mgbazinye, ma ọ bụ tinye ego n'ụlọ dị ọkachamanwa n'obodo ndị na-eto eto nke Nigeria — ndepụta akwadoro, ndị ọrụ ntụkwasị obi, azụmahịa dị mfe.", searchPlaceholder: "Chọọ ọnọdụ, ebe obibi, ma ọ bụ ụdị ụlọ...", sortNewest: "Nhazi: Ọhụrụ Kachasị", sortLowHigh: "Ọnụahịa: Nta ruo Nnukwu", sortHighLow: "Ọnụahịa: Nnukwu ruo Nta", listingsAvailable: "Ndepụta Dịnụ", saved: "echekwara", bookInspection: "Depụta Nlele", confirmBooking: "Kwenye Ndepụta Nlele", whyBadge: "Gịnị Kpatara FCC Ụlọ Ahịa", whyTitle1: "Ụzọ Dị Mma Kachasị ịZụta", whyTitle2: "Ụlọ na Nigeria", propFor: "Maka", beds: "Ụlọ Ụra", baths: "Ụlọ Ọcha", popular: "Ndị Ama Ama" },
    careers: { heroBadge: "Sonye Ndị Ọrụ Anyị", heroTitle1: "Wuo Ọrụ Gị.", heroTitle2: "Wuo Ọdịnihu Afrịka.", heroSubtitle: "Sonye ndị ọkachamara 1,000+ na-ahazi gburugburu ụlọ Afrịka. FCC na-enye uto ọrụ, ụgwọ ọma, na ohere ịrụ ọrụ n'ọrụ ama ama.", openRolesBadge: "Ọrụ Dị Mfe", openRolesTitle: "Ohere Dịnụ Ugbu A", artisanBadge: "Database Ndị Ọka Aka", artisanTitle1: "Ị Bụ Onye Ọrụ", artisanTitle2: "Nkà Dị Mma?", artisanSubtitle: "Sonye database ndị ọrụ nwu ụlọ kacha mma na Nigeria. Chọta ọrụ, nweta ọla ọzọ, ma wuo ọrụ gị.", formBadge: "Tinye Akwụkwọ", formTitle: "Zipu Akwụkwọ Arịọ Gị", tabJob: "Arịọ Ọrụ", tabLabor: "Ndepụta Ndị Ọrụ", tabContractor: "Ndepụta Contractor", submitApplication: "Zipu Arịọ" },
    contact: { heroBadge: "Kpọtụrụ Anyị", heroTitle1: "Ka Anyị Wuo", heroTitle2: "Ọhụụ Gị Ọnụ", heroSubtitle: "Ị dị njikere ịmalite ọrụ? Ị na-achọ ụlọ ị ga-etinye ego? Ị chọọ ngwọta ndị ọrụ? Ndị ọrụ anyị dị njikere ịzaghachi n'ime awa 24.", sendMessage: "Ziga Anyị Ozi", messageSent: "Ozi Ezigara!", thankYou: "Daalụ maka ịkpọtụrụ anyị. Ndị ọrụ anyị ga-azaghachi n'ime awa 24.", sendAnother: "Ziga Ozi Ọzọ", fullName: "Aha Zuru Oke", emailAddress: "Adreesị Email", phoneNumber: "Nọmba Ekwentị", serviceRequired: "Ọrụ Achọrọ", estimatedBudget: "Ego Atụtụ", projectDescription: "Nkọwa Ọrụ", projectDescPlaceholder: "Kọwa anyị maka ọrụ gị, oge, ọnọdụ, na ihe ọ bụla pụtara ìhè...", directContacts: "Kọntaktị Ozugbo", responseTime: "Oge Ịzaghachi", generalEnquiries: "Ajụjụ Izugbe", projectQuotations: "Ọnụahịa Ọrụ", emergencySupport: "Nkwado Mberede Saịtị", siteEmergency: "Mberede Saịtị?", siteEmergencyDesc: "Kpọọ akara mberede anyị na-arụ ọrụ awa 24/7 maka ihe mberede saịtị.", officesBadge: "Ọfịs Anyị", officesTitle1: "Hụ Anyị", officesTitle2: "N'Naịjịrịa Niile" },
    footer: { tagline: "Otu ụlọ ọrụ. Ohere enweghị njedebe. Na-ewu obodo na ịmepụta ọdịnihu n'Afrịka niile." },
  },

  /* ═══════════════ HAUSA ═══════════════ */
  ha: {
    nav: { home: "Gida", about: "Game da Mu", services: "Ayyukanmu", projects: "Ayyukan Ginin", properties: "Dukiyoyi", careers: "Aiki", team: "Tawin Mu", contact: "Tuntube Mu", getQuote: "Sami Farashin" },
    common: { learnMore: "Ƙara Sani", contactUs: "Tuntube Mu", viewAll: "Duba Duka", startProject: "Fara Aikinku", getQuote: "Sami Farashin", viewProjects: "Duba Ayyukanmu", readMore: "Karanta Ƙari", submit: "Aika", calculate: "Ƙididdiga Farashin", reset: "Sake Fara", search: "Nema", filters: "Tacewar", bookInspection: "Yi Rajista don Duba", applyNow: "Nemi Aiki Yanzu", sendMessage: "Aika Saƙo", allRightsReserved: "Ana kiyaye duk hakki.", buildingCities: "Gina Birrane. Ƙirƙirar Makoma.", privacyPolicy: "Manufar Sirri", termsOfService: "Sharuɗɗan Sabis", emergencyLine: "Layin Gaggawa", ourDivisions: "Sassan Mu", quickLinks: "Hanyoyin Gaggawa" },
    home: { heroBadge: "Gina Birrane. Ƙirƙirar Makoma.", heroH1a: "Kamfanin Ginin", heroH1b: "Da Ya Fi", heroH1c: "Komai a Afirka", heroSubtitle: "FCC Fore-City Construction yana isar da ginin ƙasa da ƙasa, gidaje, da maganin dukiyar gabaɗaya — daga tushe zuwa ƙarshe, a cikin birrane mafi girma na Afirka.", heroFindProperty: "Nemo Dukiya", statProjects: "Ayyukan Da Aka Kammala", statWorkforce: "Ƙwararrun Ma'aikata", statClients: "Abokan Ciniki Masu Farin Ciki", statProperties: "Gidaje Da Aka Isar", servicesBadge: "Abin da Muke Yi", servicesTitle1: "Sassan Ƙarfi Biyar.", servicesTitle2: "Kamfani Ɗaya.", servicesSubtitle: "Daga farawa har zuwa mika makullin, muna ba da maganin muhalli gaba ɗaya a ƙarƙashin gidan da.", whyBadge: "Me Yasa Za Ka Zaɓi FCC", whyTitle1: "Amintaccen Mafi Girma", whyTitle2: "Kamfanonin Najeriya", whyBody: "A cikin shekaru 15+, mun gina tarihin amana, inganci, da isar da ayyuka a lokaci. Hanyarmu ta haɗaɗɗe na nufin ƙarancin masu aikin gini, kammala da sauri, da sakamako mafi kyau.", portfolioBadge: "Ayyukanmu", portfolioTitle: "Ayyukan Da Aka Zaɓa", featuredProjects: "Duk Ayyukan", testimonialsBadge: "Shaidu", testimonialsTitle: "Abin da Abokan Cinikinmu Ke Cewa", ctaTitle1: "Kun Shirya Gini", ctaTitle2: "Wani Abu Na Musamman?", ctaSubtitle: "Daga shawara ta farko zuwa mika aikin, FCC tana tare da ku a kowane mataki.", ctaAbout: "Game da FCC", trustedBy: "Amintaccen Jagorori na Masana'antu" },
    about: { heroBadge: "Labarin Mu", heroTitle1: "Gina Afirka,", heroTitle2: "Aiki ɗaya a Kowane Lokaci", heroSubtitle: "FCC ita ce kamfanin ginin da ya fi haɗaɗɗe a Najeriya — yana isar da gine-gine, gidaje, sarrafa dukiya, ƙawata gida, da maganin ma'aikata.", missionLabel: "Manufarmu", visionLabel: "Hangen Nesanmu", valuesBadge: "Ƙimominmu", valuesTitle1: "Abin da Ke Motsa Mu", valuesTitle2: "Kowace Rana", certBadge: "Takardu", certTitle1: "An Tabbatar &", certTitle2: "An Amince a Duniya", certSubtitle: "Takardunanmu ba kawai alamu ba ne — su shaida ne na sadaukar da mu ga inganci da ka'idodin aminci na duniya.", workforceBadge: "Ma'aikatanmu", workforceTitle1: "Ƙwararrun 1,000+.", workforceTitle2: "Ƙungiya ɗaya Ta Ƙarfi.", timelineBadge: "Tafiyarmu", timelineTitle1: "Shekaru 15 na", timelineTitle2: "Gina Ƙwarewa", leadershipBadge: "Jagora", leadershipTitle: "Haɗu da Ƙungiyar", ctaTitle1: "Mu Gina Wani Abu", ctaTitle2: "Mai Kyau Tare", ctaSubtitle: "Ko kuna fara sabon aiki ko kuna neman saka hannun jari a gidaje, FCC na shirye." },
    services: { heroBadge: "Ayyukanmu", heroTitle1: "Sassan Biyar.", heroTitle2: "Yuwuwar Marasa Iyaka.", heroSubtitle: "Daga farawa zuwa sarrafa dukiya, FCC ta rufe kowane mataki na yanayin gini ɗaya tare.", divisionLabel: "Sashe", ctaTitle1: "Kuna Buƙatar", ctaTitle2: "Jakar Sabis Na Musamman?", ctaSubtitle: "Muna daidaita sabisominmu da buƙatun aikinku na musamman da kasafin ku. Yi magana da ƙungiyarmu yau.", divisionNames: ["Gina Gine-gine & Injiniya", "Gidaje & Dukiya", "Sarrafa Gidaje & Dukiya", "Ƙawata Gida & Kammalawa", "Ma'aikata & Kayan Aiki"] },
    projects: { heroBadge: "Ayyukanmu", heroTitle1: "Ayyuka 500+.", heroTitle2: "Babu Rangwame.", heroSubtitle: "Daga gidajen zama zuwa ababen more rayuwa na ƙasa — kowane aiki a cikin jerin ayyukanmu yana wakiltar sadaukarwa ga inganci, ƙirƙira, da isar a lokaci.", filterAll: "Duka", enquire: "Yi Tambaya", ctaTitle1: "Aikinku Na Iya Zama", ctaTitle2: "Ƙirƙirar Mu ta Gaba", ctaSubtitle: "Mu tattauna ra'ayinku mu kuma juya shi zuwa aiki mai kyau.", startProject: "Fara Aiki", statValue: "Jimillar Ƙimar Kwangilar", statContract: "Ayyukan Da Aka Kammala", statStates: "Jihohi Da Aka Rufe", statDelivery: "Adadin Isar a Lokaci" },
    properties: { heroBadge: "Kasuwar Dukiya", heroTitle1: "Sami Dukiyarku", heroTitle2: "Ta Musamman", heroSubtitle: "Saya, haya, ko saka hannun jari a gidaje masu inganci a cikin biranen Najeriya mafi girma — jerin ayyukan da aka tabbatar, wakilan amana, kasuwancin sauƙi.", searchPlaceholder: "Nemo wurin, gida, ko nau'in dukiya...", sortNewest: "Tsara: Sabon", sortLowHigh: "Farashi: Ƙananan zuwa Girma", sortHighLow: "Farashi: Girma zuwa Ƙananan", listingsAvailable: "Jerin Ayyukan Akwai", saved: "an adana", bookInspection: "Yi Rajista don Duba", confirmBooking: "Tabbatar da Rajistar Duba", whyBadge: "Me Yasa FCC Dukiya", whyTitle1: "Hanyar Mafi Aminci don Saya", whyTitle2: "Dukiya a Najeriya", propFor: "Don", beds: "Ɗaki", baths: "Wanka", popular: "Mashahuran" },
    careers: { heroBadge: "Shiga Ƙungiyarmu", heroTitle1: "Gina Aikinku.", heroTitle2: "Gina Makomar Afirka.", heroSubtitle: "Shiga ƙungiyar ƙwararrun 1,000+ da ke tsara muhalli na ginin Afirka. FCC tana ba da bunƙasar aiki, albashi mai gasa, da damar aiki a kan manyan ayyuka.", openRolesBadge: "Buɗaɗɗun Ayyuka", openRolesTitle: "Damammaki Na Yanzu", artisanBadge: "Bayanan Masu Sana'a", artisanTitle1: "Kai Ma'aikacin", artisanTitle2: "Sana'a Ne?", artisanSubtitle: "Shiga bayanan ma'aikatan gini mafi girma a Najeriya. Sami ayyuka, samu ƙarin kuɗi, ka gina aikinsa.", formBadge: "Yi Amfani Yanzu", formTitle: "Miƙa Aikacen Ku", tabJob: "Aikacen Aiki", tabLabor: "Rajista Ma'aikata", tabContractor: "Rajista Masu Kwangila", submitApplication: "Miƙa Aikace-aikace" },
    contact: { heroBadge: "Tuntube Mu", heroTitle1: "Mu Gina", heroTitle2: "Hangen Nesanku Tare", heroSubtitle: "Kun shirya fara aiki? Kuna neman dukiyar saka hannun jari? Kuna buƙatar ma'aikatan aiki? Ƙungiyarmu na shirye ta amsa a cikin awanni 24.", sendMessage: "Aiko Mana Saƙo", messageSent: "An Aika Saƙo!", thankYou: "Na gode da tuntuɓar mu. Ƙungiyarmu za ta amsa a cikin awanni 24.", sendAnother: "Aika Wani Saƙo", fullName: "Cikakken Suna", emailAddress: "Adireshin Email", phoneNumber: "Lambar Waya", serviceRequired: "Sabis Da Ake Buƙata", estimatedBudget: "Kasafin Kuɗi", projectDescription: "Bayanin Aiki", projectDescPlaceholder: "Faɗa mana game da aikinku, lokaci, wurin, da kowane buƙatu na musamman...", directContacts: "Lambobin Tuntuɓa", responseTime: "Lokacin Amsa", generalEnquiries: "Tambayoyi Gabaɗaya", projectQuotations: "Farashin Aiki", emergencySupport: "Tallafin Gaggawa", siteEmergency: "Gaggawa a Wurin Aiki?", siteEmergencyDesc: "Kira layin gaggawarmu na 24/7 don abubuwan gaggawa a wurin aiki.", officesBadge: "Ofisoshinmu", officesTitle1: "Samu Mu", officesTitle2: "A Ko'ina a Najeriya" },
    footer: { tagline: "Kamfani ɗaya. Yuwuwar marasa iyaka. Gina birrane da ƙirƙirar makoma a duk faɗin Afirka." },
  },

  /* ═══════════════ YORUBA ═══════════════ */
  yo: {
    nav: { home: "Ilé", about: "Nípa Wa", services: "Àwọn Iṣẹ́", projects: "Àwọn Iṣẹ́ Wa", properties: "Ohun Ini", careers: "Iṣẹ́", team: "Ẹgbẹ́ Wa", contact: "Kan Sí Wa", getQuote: "Gba Ìdíyè" },
    common: { learnMore: "Kọ́ Sí i", contactUs: "Kan Sí Wa", viewAll: "Wo Gbogbo", startProject: "Bẹ̀rẹ̀ Iṣẹ́ Rẹ", getQuote: "Gba Ìdíyè", viewProjects: "Wo Àwọn Iṣẹ́ Wa", readMore: "Ka Sí i", submit: "Firanṣẹ́", calculate: "Ṣe Iṣiro Iye", reset: "Tún Bẹ̀rẹ̀", search: "Wá", filters: "Àwọn Àlẹ̀mọ́", bookInspection: "Dépò Àyẹ̀wò", applyNow: "Bẹ̀rẹ̀ Ṣe Àbẹ̀wò", sendMessage: "Firanṣẹ́ Ọ̀rọ̀", allRightsReserved: "Gbogbo ẹ̀tọ́ ni a ń tọ́jú.", buildingCities: "Kíkọ́ Àwọn Ìlú. Ṣíṣẹ̀dá Ọjọ́ Ọ̀la.", privacyPolicy: "Ìlànà Ìkọ̀kọ̀", termsOfService: "Àwọn Ọ̀rọ̀ Iṣẹ́", emergencyLine: "Nọ́mbà Pàjáwìrì", ourDivisions: "Àwọn Ẹ̀ka Wa", quickLinks: "Àwọn Àsopọ̀ Yára" },
    home: { heroBadge: "Kíkọ́ Àwọn Ìlú. Ṣíṣẹ̀dá Ọjọ́ Ọ̀la.", heroH1a: "Àjọ Kíkọ́ Ilé", heroH1b: "Tó Dára Jùlọ", heroH1c: "Ní Áfríkà", heroSubtitle: "FCC Fore-City Construction n-jọ̀gbọ̀n kíkọ́ ilé àgbáyé, ohun ini, àti ọgbọ́n dídàpọ̀ — láti ìpìlẹ̀ dé òpin, ní àwọn ìlú tó ń dàgbà jùlọ ní Áfríkà.", heroFindProperty: "Wá Ohun Ini", statProjects: "Àwọn Iṣẹ́ Tí A Parí", statWorkforce: "Àwọn Òṣìṣẹ́ Ọlọ́gbọ́n", statClients: "Àwọn Aládùúgbò Tó Dùn", statProperties: "Ohun Ini Tí A Jíjẹ́", servicesBadge: "Ohun Tí A Ń Ṣe", servicesTitle1: "Àwọn Ẹ̀ka Agbára Márùn-ún.", servicesTitle2: "Àjọ Kan.", servicesSubtitle: "Láti ìbẹ̀rẹ̀ dé fífún àwọn bọ́tìnnì, a n-pèsè ojútùú gbogbo àyíká ìkọ́lé lábẹ́ àárọ̀ kan.", whyBadge: "Ìdí Tí O Fi Yẹ Kí O Yan FCC", whyTitle1: "Àwọn Ìdílé Tó Tọ́kàntọ́kàn", whyTitle2: "Ní Nàìjíríà Gbé FCC", whyBody: "Ní ọdún 15+ sẹ́yìn, a ti kọ́ ogún ìgbẹ́kẹ̀lé, ìtọ́jú, àti fífún ní àkókò. Ọ̀nà wa tó dàpọ̀ túmọ̀ sí àwọn adéhùn òṣìṣẹ́ kéékéèkéé, ìparí yára, àti àbájáde tó dára.", portfolioBadge: "Àwọn Iṣẹ́ Wa", portfolioTitle: "Àwọn Iṣẹ́ Tó Gbajúmọ̀", featuredProjects: "Gbogbo Àwọn Iṣẹ́", testimonialsBadge: "Ẹ̀rí", testimonialsTitle: "Ohun Tí Àwọn Aládùúgbò Wa Sọ", ctaTitle1: "Ṣé O Ṣetán Láti Kọ́", ctaTitle2: "Nkan Àgbàyanu?", ctaSubtitle: "Láti ìjíròrò àkọ́kọ́ rẹ dé ìfówópamọ́ iṣẹ́, FCC wà pẹ̀lú rẹ ní gbogbo ìgbésẹ̀.", ctaAbout: "Nípa FCC", trustedBy: "Àwọn Aṣáájú Ilé Iṣẹ́ Tí Wọn Gbẹ́kẹ̀lé" },
    about: { heroBadge: "Ìtàn Wa", heroTitle1: "Kíkọ́ Áfríkà,", heroTitle2: "Iṣẹ́ Kan Ní Àkókò Kọ̀ọ̀kan", heroSubtitle: "FCC jẹ́ àjọ kíkọ́ ilé tó dàpọ̀ jùlọ ní Nàìjíríà — n-jọ̀gbọ̀n kíkọ́ ilé, ohun ini, ìṣàkóso dukia, ohun ọṣọ inú ilé, àti ojútùú òṣìṣẹ́.", missionLabel: "Ìgbẹ́kẹ̀lé Wa", visionLabel: "Ìríran Wa", valuesBadge: "Àwọn Iye Wa", valuesTitle1: "Ohun Tó Ń Mú Wa Gbógun Ti", valuesTitle2: "Ní Ọjọ́ Kọ̀ọ̀kan", certBadge: "Àwọn Ìfọwọ́sí", certTitle1: "A Ti Fọwọ́sí &", certTitle2: "A Mọ̀ Ní Àgbáyé", certSubtitle: "Àwọn ìfọwọ́sí wa kìí ṣe àwọn àmì kan nìkan — wọn jẹ́ ẹ̀rí ifaramọ́ wa sí àwọn ìwọ̀n didara àgbáyé.", workforceBadge: "Àwọn Òṣìṣẹ́ Wa", workforceTitle1: "Àwọn Akíkanjú 1,000+.", workforceTitle2: "Ẹgbẹ́ Kan Tó Lágbára.", timelineBadge: "Ìrìnnà Wa", timelineTitle1: "Ọdún 15 ti", timelineTitle2: "Ìkọ́lé Àgbàyanu", leadershipBadge: "Ìdarí", leadershipTitle: "Pàdé Ẹgbẹ́ Wa", ctaTitle1: "Jẹ́ Ka Kọ́ Nkan", ctaTitle2: "Tó Dára Papọ̀", ctaSubtitle: "Bóyá o ń bẹ̀rẹ̀ iṣẹ́ tuntun tàbí o fẹ́ gbéjókòó sínú ohun ini, FCC ṣetán." },
    services: { heroBadge: "Àwọn Iṣẹ́ Wa", heroTitle1: "Àwọn Ẹ̀ka Márùn-ún.", heroTitle2: "Àwọn Àǹfààní Àìlópin.", heroSubtitle: "Láti ìbẹ̀rẹ̀ dé ìṣàkóso dukia, FCC bo gbogbo ìpele ti àyíká kíkọ́ ilé lábẹ́ àárọ̀ kan.", divisionLabel: "Ẹ̀ka", ctaTitle1: "O Nílò Àpò Iṣẹ́", ctaTitle2: "Tó Pàtàkì?", ctaSubtitle: "A ṣe àkójọpọ̀ àwọn iṣẹ́ wa sí àwọn àìní iṣẹ́ rẹ àti isuna. Bá ẹgbẹ́ wa sọ̀rọ̀ lónìí.", divisionNames: ["Kíkọ́ Ilé & Ìmọ̀ Ẹ̀rọ", "Ohun Ini & Dúkia", "Ìṣàkóso Dúkia & Ohun Ini", "Ohun Ọṣọ Inú Ilé & Ìparí", "Àwọn Òṣìṣẹ́ & Ohun èlò"] },
    projects: { heroBadge: "Àwọn Iṣẹ́ Wa", heroTitle1: "Iṣẹ́ 500+.", heroTitle2: "Kò Sí Ìdèdè.", heroSubtitle: "Láti àwọn ìdílé dé àwọn amayederun orílẹ̀-èdè — iṣẹ́ kọ̀ọ̀kan nínú àpamọ́ wa ṣàkójọpọ̀ ìfaramọ́ sí ìdánilẹ́kọ̀ọ́, ìmọ̀-ẹ̀rọ, àti ìfún ní àkókò.", filterAll: "Gbogbo", enquire: "Bẹ̀rẹ̀ Ìbéèrè", ctaTitle1: "Iṣẹ́ Rẹ Le Jẹ́", ctaTitle2: "Iṣẹ́ Wa Tó Ń Bọ̀", ctaSubtitle: "Jẹ́ ka jíròrò ìríran rẹ a sì yí padà sí iṣẹ́ tó gbajúmọ̀.", startProject: "Bẹ̀rẹ̀ Iṣẹ́", statValue: "Iye Àdéhùn Gbogbo", statContract: "Àwọn Iṣẹ́ Tí A Parí", statStates: "Àwọn Ìpínlẹ̀ Tí A Bo", statDelivery: "Ìwọ̀n Ìfún Ní Àkókò" },
    properties: { heroBadge: "Ọjà Ohun Ini", heroTitle1: "Wá Ohun Ini", heroTitle2: "Tó Péye Fún Ọ", heroSubtitle: "Ra, yálà, tàbí gbéjókòó sínú àwọn ohun ini tó gbajúmọ̀ ní àwọn ìlú tó ń dàgbà jùlọ ní Nàìjíríà — àwọn àkójọ tó jẹrí, àwọn aṣojú tó ìgbẹ́kẹ̀lé, àwọn ìṣòwò tó rọrùn.", searchPlaceholder: "Wá ibùdó, ohun ini, tàbí irú dúkia...", sortNewest: "Tò: Tuntun Jùlọ", sortLowHigh: "Iye: Kéékéèkéé sí Ńlá", sortHighLow: "Iye: Ńlá sí Kéékéèkéé", listingsAvailable: "Àwọn Àkójọ Tó Wà", saved: "fipamọ́", bookInspection: "Dépò Àyẹ̀wò", confirmBooking: "Jẹ́ri Àyẹ̀wò Dépò", whyBadge: "Ìdí Tí FCC Ohun Ini", whyTitle1: "Ọ̀nà Tó Pàálà Jùlọ Láti Ra", whyTitle2: "Dúkia Ní Nàìjíríà", propFor: "Fún", beds: "Yàrá Sinmi", baths: "Yàrá Ìwẹ̀", popular: "Tó Gbajúmọ̀" },
    careers: { heroBadge: "Darapọ̀ Mọ́ Ẹgbẹ́ Wa", heroTitle1: "Kọ́ Iṣẹ́ Rẹ.", heroTitle2: "Kọ́ Ọjọ́ Ọ̀la Áfríkà.", heroSubtitle: "Darapọ̀ mọ́ ẹgbẹ́ àwọn akíkanjú 1,000+ tó ń ṣe àkójọpọ̀ àyíká kíkọ́ Áfríkà. FCC n-pèsè idàgbàsókè iṣẹ́, ọ̀yà olóore, àti àǹfààní láti ṣiṣẹ́ ní àwọn iṣẹ́ pàtàkì.", openRolesBadge: "Àwọn Ipa Tó Ṣí", openRolesTitle: "Àwọn Àǹfààní Tó Wà", artisanBadge: "Àkójọpọ̀ Àwọn Òṣìṣẹ́", artisanTitle1: "Ṣé O Jẹ́ Òṣìṣẹ́", artisanTitle2: "Tó Ní Ọgbọ́n?", artisanSubtitle: "Darapọ̀ mọ́ àkójọpọ̀ àwọn òṣìṣẹ́ kíkọ́ ilé tó dára jùlọ ní Nàìjíríà. Rí iṣẹ́ pàdé, jèrè sí i, kọ́ iṣẹ́ rẹ.", formBadge: "Bẹ̀rẹ̀ Ṣe Àbẹ̀wò", formTitle: "Firanṣẹ́ Àbẹ̀wò Rẹ", tabJob: "Àbẹ̀wò Iṣẹ́", tabLabor: "Ìdásílẹ̀ Òṣìṣẹ́", tabContractor: "Ìforúkọsílẹ̀ Aṣàdéhùn", submitApplication: "Firanṣẹ́ Àbẹ̀wò" },
    contact: { heroBadge: "Kan Sí Wa", heroTitle1: "Jẹ́ Ka Kọ́", heroTitle2: "Ìríran Rẹ Papọ̀", heroSubtitle: "Ṣetán láti bẹ̀rẹ̀ iṣẹ́? O ń wá ohun ini láti gbéjókòó sínú? O nílò ojútùú òṣìṣẹ́? Ẹgbẹ́ wa ṣetán láti dáhùn láàárọ̀ 24.", sendMessage: "Fi Ọ̀rọ̀ Ránṣẹ́ Sí Wa", messageSent: "A Ti Firanṣẹ́ Ọ̀rọ̀!", thankYou: "Ẹ ṣéun fún ìkán sí wa. Ẹgbẹ́ wa yóò dáhùn láàárọ̀ 24.", sendAnother: "Fi Ọ̀rọ̀ Mìíràn Ránṣẹ́", fullName: "Orúkọ Kíkún", emailAddress: "Àdírẹ́sì Ìmẹ̀lẹ̀", phoneNumber: "Nọ́mbà Fóònù", serviceRequired: "Iṣẹ́ Tó Nílò", estimatedBudget: "Isuna Àfiyèsí", projectDescription: "Àpèjúwe Iṣẹ́", projectDescPlaceholder: "Sọ fún wa nípa iṣẹ́ rẹ, àkókò, ibùdó, àti àwọn àìní pàtàkì...", directContacts: "Àwọn Ìkànsí Tààrà", responseTime: "Àwọn Àkókò Ìdáhùn", generalEnquiries: "Àwọn Ìbéèrè Gbogbogbò", projectQuotations: "Àwọn Ìdíyè Iṣẹ́", emergencySupport: "Àtìlẹ́yìn Pàjáwìrì", siteEmergency: "Pàjáwìrì Ibi Iṣẹ́?", siteEmergencyDesc: "Pe ọ̀nà pàjáwìrì wa tó ń ṣiṣẹ́ 24/7 fún àwọn ọ̀rọ̀ pàjáwìrì ibi iṣẹ́.", officesBadge: "Àwọn Ọfíìsì Wa", officesTitle1: "Wá Wa", officesTitle2: "Ní Gbogbo Nàìjíríà" },
    footer: { tagline: "Àjọ kan. Àwọn àǹfààní àìlópin. Kíkọ́ àwọn ìlú àti ṣíṣẹ̀dá ọjọ́ ọ̀la ní gbogbo Áfríkà." },
  },

  /* ═══════════════ FRENCH ═══════════════ */
  fr: {
    nav: { home: "Accueil", about: "À Propos", services: "Services", projects: "Projets", properties: "Propriétés", careers: "Carrières", team: "Notre Équipe", contact: "Contact", getQuote: "Obtenir un Devis" },
    common: { learnMore: "En Savoir Plus", contactUs: "Nous Contacter", viewAll: "Voir Tout", startProject: "Démarrer Votre Projet", getQuote: "Obtenir un Devis", viewProjects: "Voir Nos Projets", readMore: "Lire Plus", submit: "Soumettre", calculate: "Calculer", reset: "Réinitialiser", search: "Rechercher", filters: "Filtres", bookInspection: "Réserver une Inspection", applyNow: "Postuler Maintenant", sendMessage: "Envoyer un Message", allRightsReserved: "Tous droits réservés.", buildingCities: "Bâtir des Villes. Créer des Avenirs.", privacyPolicy: "Politique de Confidentialité", termsOfService: "Conditions d'Utilisation", emergencyLine: "Ligne d'Urgence", ourDivisions: "Nos Divisions", quickLinks: "Liens Rapides" },
    home: { heroBadge: "Bâtir des Villes. Créer des Avenirs.", heroH1a: "La Première", heroH1b: "Puissance de Construction", heroH1c: "d'Afrique", heroSubtitle: "FCC Fore-City Construction offre des solutions mondiales en construction, immobilier, et gestion intégrée de propriétés — de la fondation à la finition, dans les villes à plus forte croissance d'Afrique.", heroFindProperty: "Trouver une Propriété", statProjects: "Projets Réalisés", statWorkforce: "Main-d'Œuvre Qualifiée", statClients: "Clients Satisfaits", statProperties: "Propriétés Livrées", servicesBadge: "Ce Que Nous Faisons", servicesTitle1: "Cinq Divisions Puissantes.", servicesTitle2: "Une Seule Entreprise.", servicesSubtitle: "Du premier coup de pioche à la remise des clés, nous offrons des solutions complètes sous un même toit.", whyBadge: "Pourquoi Choisir FCC", whyTitle1: "La Confiance des Plus Grands", whyTitle2: "du Nigéria", whyBody: "En 15+ ans, nous avons bâti un héritage de confiance, de qualité et de livraison dans les délais. Notre approche intégrée signifie moins de sous-traitants, des délais plus courts et de meilleurs résultats.", portfolioBadge: "Portfolio", portfolioTitle: "Projets en Vedette", featuredProjects: "Tous les Projets", testimonialsBadge: "Témoignages", testimonialsTitle: "Ce Que Disent Nos Clients", ctaTitle1: "Prêt à Construire", ctaTitle2: "Quelque Chose d'Extraordinaire?", ctaSubtitle: "De la première consultation à la remise du projet, FCC est à vos côtés à chaque étape.", ctaAbout: "À Propos de FCC", trustedBy: "La Confiance des Leaders du Secteur" },
    about: { heroBadge: "Notre Histoire", heroTitle1: "Construire l'Afrique,", heroTitle2: "Un Projet à la Fois", heroSubtitle: "FCC est la société la plus intégrée dans le secteur de la construction au Nigéria — offrant construction, immobilier, gestion de propriétés, design intérieur et solutions de main-d'œuvre.", missionLabel: "Notre Mission", visionLabel: "Notre Vision", valuesBadge: "Nos Valeurs", valuesTitle1: "Ce Qui Nous Motive", valuesTitle2: "Chaque Jour", certBadge: "Accréditations", certTitle1: "Certifié &", certTitle2: "Accrédité Internationalement", certSubtitle: "Nos certifications ne sont pas de simples badges — elles témoignent de notre engagement envers les normes internationales de qualité et de sécurité.", workforceBadge: "Notre Effectif", workforceTitle1: "1 000+ Professionnels.", workforceTitle2: "Une Équipe Inarrêtable.", timelineBadge: "Notre Parcours", timelineTitle1: "15 Ans de", timelineTitle2: "Excellence en Construction", leadershipBadge: "Direction", leadershipTitle: "Rencontrez l'Équipe", ctaTitle1: "Construisons Quelque Chose", ctaTitle2: "de Grand Ensemble", ctaSubtitle: "Que vous lanciez un nouveau projet ou cherchiez à investir, FCC est prêt." },
    services: { heroBadge: "Nos Services", heroTitle1: "Cinq Divisions.", heroTitle2: "Des Possibilités Illimitées.", heroSubtitle: "Du premier coup de pioche à la gestion de propriétés, FCC couvre chaque étape du cycle de l'environnement bâti sous une marque intégrée.", divisionLabel: "Division", ctaTitle1: "Besoin d'un Package", ctaTitle2: "de Services Personnalisé?", ctaSubtitle: "Nous adaptons nos services à vos besoins et à votre budget. Parlez à notre équipe aujourd'hui.", divisionNames: ["Construction & Ingénierie", "Immobilier & Propriété", "Gestion de Propriétés", "Design Intérieur & Finition", "Main-d'Œuvre & Équipements"] },
    projects: { heroBadge: "Notre Portfolio", heroTitle1: "500+ Projets.", heroTitle2: "Zéro Compromis.", heroSubtitle: "Des résidences aux infrastructures nationales — chaque projet représente un engagement envers l'excellence, l'innovation et la livraison dans les délais.", filterAll: "Tous", enquire: "Se Renseigner", ctaTitle1: "Votre Projet Pourrait Être", ctaTitle2: "Notre Prochain Chef-d'Œuvre", ctaSubtitle: "Discutons de votre vision et transformons-la en projet primé.", startProject: "Démarrer un Projet", statValue: "Valeur Totale des Contrats", statContract: "Projets Réalisés", statStates: "États Couverts", statDelivery: "Taux de Livraison à Temps" },
    properties: { heroBadge: "Marché Immobilier", heroTitle1: "Trouvez Votre", heroTitle2: "Propriété Idéale", heroSubtitle: "Achetez, louez ou investissez dans des propriétés premium dans les villes à forte croissance du Nigéria — annonces vérifiées, agents de confiance, transactions fluides.", searchPlaceholder: "Rechercher par lieu, domaine ou type de propriété...", sortNewest: "Trier: Plus Récent", sortLowHigh: "Prix: Croissant", sortHighLow: "Prix: Décroissant", listingsAvailable: "Annonces Disponibles", saved: "sauvegardés", bookInspection: "Réserver une Inspection", confirmBooking: "Confirmer la Réservation", whyBadge: "Pourquoi FCC Immobilier", whyTitle1: "La Façon la Plus Sûre d'Acheter", whyTitle2: "une Propriété au Nigéria", propFor: "Pour", beds: "Chambre", baths: "Salle de Bain", popular: "Populaire" },
    careers: { heroBadge: "Rejoignez Notre Équipe", heroTitle1: "Construisez Votre Carrière.", heroTitle2: "Construisez l'Avenir de l'Afrique.", heroSubtitle: "Rejoignez une équipe de 1 000+ professionnels qui façonnent l'environnement bâti africain. FCC offre évolution de carrière, rémunération compétitive et opportunités sur des projets emblématiques.", openRolesBadge: "Postes Ouverts", openRolesTitle: "Opportunités Actuelles", artisanBadge: "Base de Données Artisans", artisanTitle1: "Êtes-vous un Professionnel", artisanTitle2: "du Secteur?", artisanSubtitle: "Rejoignez la principale base de données de main-d'œuvre du Nigéria. Trouvez des projets, gagnez plus, et construisez votre carrière.", formBadge: "Postuler Maintenant", formTitle: "Soumettre Votre Candidature", tabJob: "Candidature Emploi", tabLabor: "Inscription Main-d'Œuvre", tabContractor: "Inscription Sous-Traitant", submitApplication: "Soumettre la Candidature" },
    contact: { heroBadge: "Nous Contacter", heroTitle1: "Construisons", heroTitle2: "Votre Vision Ensemble", heroSubtitle: "Prêt à lancer un projet? Cherchez une propriété d'investissement? Besoin d'une solution de main-d'œuvre? Notre équipe répondra dans les 24 heures.", sendMessage: "Envoyez-Nous un Message", messageSent: "Message Envoyé!", thankYou: "Merci de nous avoir contactés. Notre équipe répondra dans les 24 heures.", sendAnother: "Envoyer un Autre Message", fullName: "Nom Complet", emailAddress: "Adresse Email", phoneNumber: "Numéro de Téléphone", serviceRequired: "Service Requis", estimatedBudget: "Budget Estimé", projectDescription: "Description du Projet", projectDescPlaceholder: "Décrivez votre projet, délais, localisation et exigences spécifiques...", directContacts: "Contacts Directs", responseTime: "Délais de Réponse", generalEnquiries: "Demandes Générales", projectQuotations: "Devis de Projet", emergencySupport: "Urgence sur Site", siteEmergency: "Urgence sur Site?", siteEmergencyDesc: "Appelez notre ligne d'urgence 24/7 pour les situations urgentes sur site.", officesBadge: "Nos Bureaux", officesTitle1: "Trouvez-Nous", officesTitle2: "au Nigéria" },
    footer: { tagline: "Une entreprise. Des possibilités infinies. Bâtir des villes et créer des avenirs à travers l'Afrique." },
  },

  /* ═══════════════ CHINESE ═══════════════ */
  zh: {
    nav: { home: "首页", about: "关于我们", services: "服务", projects: "项目", properties: "房产", careers: "招聘", team: "团队", contact: "联系我们", getQuote: "获取报价" },
    common: { learnMore: "了解更多", contactUs: "联系我们", viewAll: "查看全部", startProject: "启动您的项目", getQuote: "获取报价", viewProjects: "查看项目", readMore: "阅读更多", submit: "提交", calculate: "计算估价", reset: "重置", search: "搜索", filters: "筛选", bookInspection: "预约看房", applyNow: "立即申请", sendMessage: "发送消息", allRightsReserved: "版权所有。", buildingCities: "建设城市。创造未来。", privacyPolicy: "隐私政策", termsOfService: "服务条款", emergencyLine: "紧急热线", ourDivisions: "我们的部门", quickLinks: "快速链接" },
    home: { heroBadge: "建设城市。创造未来。", heroH1a: "非洲最领先的", heroH1b: "建筑", heroH1c: "领军企业", heroSubtitle: "FCC Fore-City建筑公司提供世界一流的建筑、房地产和综合物业解决方案——从基础到竣工，遍及非洲发展最快的城市。", heroFindProperty: "寻找房产", statProjects: "已完成项目", statWorkforce: "专业技术人员", statClients: "满意客户", statProperties: "已交付房产", servicesBadge: "我们的业务", servicesTitle1: "五大强劲部门。", servicesTitle2: "一家公司。", servicesSubtitle: "从破土动工到交钥匙，我们在同一屋檐下提供端到端的建筑环境解决方案。", whyBadge: "为什么选择FCC", whyTitle1: "尼日利亚最大品牌", whyTitle2: "的信赖之选", whyBody: "15年以上，我们建立了信任、质量和准时交付的传承。我们的综合方法意味着更少的承包商、更快的完工和更好的成果。", portfolioBadge: "项目组合", portfolioTitle: "精选项目", featuredProjects: "所有项目", testimonialsBadge: "客户评价", testimonialsTitle: "客户怎么说", ctaTitle1: "准备好建造", ctaTitle2: "非凡之作了吗？", ctaSubtitle: "从第一次咨询到项目交付，FCC在每一步都陪伴着您。", ctaAbout: "关于FCC", trustedBy: "行业领军企业的信赖之选" },
    about: { heroBadge: "我们的故事", heroTitle1: "建设非洲，", heroTitle2: "一次一个项目", heroSubtitle: "FCC是尼日利亚最综合的建筑环境公司——在一个强大品牌下提供建筑、房地产、物业管理、室内设计和劳动力解决方案。", missionLabel: "我们的使命", visionLabel: "我们的愿景", valuesBadge: "我们的价值观", valuesTitle1: "每天驱动我们的", valuesTitle2: "核心力量", certBadge: "认证资质", certTitle1: "已认证且", certTitle2: "国际认可", certSubtitle: "我们的认证不仅仅是徽章——它们是我们对国际质量和安全标准承诺的证明。", workforceBadge: "我们的团队", workforceTitle1: "1,000+专业人士。", workforceTitle2: "一支势不可挡的团队。", timelineBadge: "我们的历程", timelineTitle1: "15年", timelineTitle2: "卓越建造", leadershipBadge: "领导团队", leadershipTitle: "认识我们的团队", ctaTitle1: "让我们共同", ctaTitle2: "创造美好", ctaSubtitle: "无论您是在启动新项目还是寻求房地产投资，FCC随时准备就绪。" },
    services: { heroBadge: "我们的服务", heroTitle1: "五大部门。", heroTitle2: "无限可能。", heroSubtitle: "从破土动工到物业管理，FCC涵盖建筑环境周期的每个阶段，汇聚于一个综合品牌之下。", divisionLabel: "部门", ctaTitle1: "需要定制化", ctaTitle2: "服务方案？", ctaSubtitle: "我们根据您的具体项目需求和预算量身定制服务。今天就与我们的团队交流。", divisionNames: ["建筑与工程", "房地产与物业", "设施与物业管理", "室内设计与装修", "劳动力与设备解决方案"] },
    projects: { heroBadge: "我们的项目组合", heroTitle1: "500+个项目。", heroTitle2: "零妥协。", heroSubtitle: "从住宅到国家基础设施——我们组合中的每个项目都代表着对卓越、创新和准时交付的承诺。", filterAll: "全部", enquire: "咨询", ctaTitle1: "您的项目可能成为", ctaTitle2: "我们的下一个杰作", ctaSubtitle: "让我们讨论您的愿景，将其打造成获奖项目。", startProject: "启动项目", statValue: "总合同价值", statContract: "已完成项目", statStates: "覆盖州数", statDelivery: "准时交付率" },
    properties: { heroBadge: "房产市场", heroTitle1: "找到您的", heroTitle2: "理想房产", heroSubtitle: "在尼日利亚发展最快的城市购买、租赁或投资优质房产——经过验证的房源、值得信赖的经纪人、无缝交易。", searchPlaceholder: "按位置、小区或房产类型搜索...", sortNewest: "排序：最新", sortLowHigh: "价格：从低到高", sortHighLow: "价格：从高到低", listingsAvailable: "个房源可用", saved: "已收藏", bookInspection: "预约看房", confirmBooking: "确认预约", whyBadge: "为什么选择FCC房产", whyTitle1: "在尼日利亚购买房产", whyTitle2: "最安全的方式", propFor: "用途", beds: "卧室", baths: "浴室", popular: "热门" },
    careers: { heroBadge: "加入我们的团队", heroTitle1: "建设您的职业。", heroTitle2: "建设非洲的未来。", heroSubtitle: "加入1,000+位塑造非洲建筑环境的专业人士团队。FCC提供职业发展、有竞争力的薪酬以及参与标志性项目的机会。", openRolesBadge: "开放职位", openRolesTitle: "当前机会", artisanBadge: "工匠数据库", artisanTitle1: "您是一位技艺精湛的", artisanTitle2: "技术专业人士吗？", artisanSubtitle: "加入尼日利亚最优质的建筑劳动力数据库。与项目匹配，增加收入，发展您的职业。", formBadge: "立即申请", formTitle: "提交您的申请", tabJob: "工作申请", tabLabor: "劳动力注册", tabContractor: "承包商注册", submitApplication: "提交申请" },
    contact: { heroBadge: "联系我们", heroTitle1: "让我们共同", heroTitle2: "实现您的愿景", heroSubtitle: "准备好启动项目？寻找投资房产？需要劳动力解决方案？我们的团队将在24小时内回复。", sendMessage: "给我们发消息", messageSent: "消息已发送！", thankYou: "感谢您的联系。我们的团队将在24小时内回复。", sendAnother: "再发一条消息", fullName: "全名", emailAddress: "电子邮件地址", phoneNumber: "电话号码", serviceRequired: "所需服务", estimatedBudget: "预算估计", projectDescription: "项目描述", projectDescPlaceholder: "告诉我们您的项目、时间表、地点和任何具体要求...", directContacts: "直接联系方式", responseTime: "响应时间", generalEnquiries: "一般咨询", projectQuotations: "项目报价", emergencySupport: "现场紧急支持", siteEmergency: "现场紧急情况？", siteEmergencyDesc: "拨打我们24/7紧急热线处理紧急现场问题。", officesBadge: "我们的办公室", officesTitle1: "在尼日利亚", officesTitle2: "找到我们" },
    footer: { tagline: "一家公司。无限可能。在非洲各地建设城市，创造未来。" },
  },

  /* ═══════════════ ARABIC ═══════════════ */
  ar: {
    nav: { home: "الرئيسية", about: "من نحن", services: "خدماتنا", projects: "مشاريعنا", properties: "العقارات", careers: "وظائف", team: "فريقنا", contact: "اتصل بنا", getQuote: "احصل على عرض سعر" },
    common: { learnMore: "اعرف أكثر", contactUs: "اتصل بنا", viewAll: "عرض الكل", startProject: "ابدأ مشروعك", getQuote: "احصل على عرض سعر", viewProjects: "عرض مشاريعنا", readMore: "اقرأ المزيد", submit: "إرسال", calculate: "احسب التقدير", reset: "إعادة تعيين", search: "بحث", filters: "تصفية", bookInspection: "احجز معاينة", applyNow: "قدّم الآن", sendMessage: "إرسال رسالة", allRightsReserved: "جميع الحقوق محفوظة.", buildingCities: "نبني المدن. نصنع المستقبل.", privacyPolicy: "سياسة الخصوصية", termsOfService: "شروط الخدمة", emergencyLine: "خط الطوارئ", ourDivisions: "أقسامنا", quickLinks: "روابط سريعة" },
    home: { heroBadge: "نبني المدن. نصنع المستقبل.", heroH1a: "القوة الرائدة", heroH1b: "في البناء", heroH1c: "عبر أفريقيا", heroSubtitle: "تقدّم FCC Fore-City Construction حلول بناء عالمية المستوى وعقارات ومشاريع متكاملة — من الأساس حتى التشطيب، عبر أسرع مدن أفريقيا نمواً.", heroFindProperty: "ابحث عن عقار", statProjects: "مشاريع منجزة", statWorkforce: "كوادر مهنية", statClients: "عملاء راضون", statProperties: "عقارات مُسلَّمة", servicesBadge: "ما نقدّمه", servicesTitle1: "خمسة أقسام متميزة.", servicesTitle2: "شركة واحدة.", servicesSubtitle: "من الحفر حتى تسليم المفاتيح، نقدّم حلولاً شاملة للبيئة المبنية تحت سقف واحد.", whyBadge: "لماذا تختار FCC", whyTitle1: "ثقة أكبر العلامات", whyTitle2: "التجارية في نيجيريا", whyBody: "على مدى 15 عاماً، بنينا إرثاً من الثقة والجودة والتسليم في الوقت المحدد. نهجنا المتكامل يعني متعاقدين أقل، إنجازاً أسرع، ونتائج أفضل.", portfolioBadge: "معرض أعمالنا", portfolioTitle: "مشاريع مميزة", featuredProjects: "جميع المشاريع", testimonialsBadge: "شهادات العملاء", testimonialsTitle: "ماذا يقول عملاؤنا", ctaTitle1: "هل أنت مستعد لبناء", ctaTitle2: "شيء استثنائي؟", ctaSubtitle: "من أول استشارة حتى تسليم المشروع، FCC معك في كل خطوة.", ctaAbout: "عن FCC", trustedBy: "موثوق من قِبَل رواد الصناعة" },
    about: { heroBadge: "قصتنا", heroTitle1: "نبني أفريقيا،", heroTitle2: "مشروعاً واحداً في كل مرة", heroSubtitle: "FCC هي أكثر شركات البيئة المبنية تكاملاً في نيجيريا — تقدّم البناء والعقارات وإدارة الممتلكات والتصميم الداخلي وحلول القوى العاملة.", missionLabel: "مهمتنا", visionLabel: "رؤيتنا", valuesBadge: "قيمنا", valuesTitle1: "ما يدفعنا للأمام", valuesTitle2: "كل يوم", certBadge: "الاعتمادات", certTitle1: "معتمد &", certTitle2: "معترف به دولياً", certSubtitle: "اعتماداتنا ليست مجرد شارات — بل هي دليل التزامنا بالمعايير الدولية للجودة والسلامة.", workforceBadge: "كوادرنا البشرية", workforceTitle1: "أكثر من 1,000 متخصص.", workforceTitle2: "فريق لا يُوقَف.", timelineBadge: "مسيرتنا", timelineTitle1: "15 عاماً من", timelineTitle2: "التميز في البناء", leadershipBadge: "القيادة", leadershipTitle: "تعرّف على الفريق", ctaTitle1: "لنبنِ شيئاً", ctaTitle2: "عظيماً معاً", ctaSubtitle: "سواء كنت تبدأ مشروعاً جديداً أو تبحث عن استثمار عقاري، FCC مستعدة." },
    services: { heroBadge: "خدماتنا", heroTitle1: "خمسة أقسام.", heroTitle2: "إمكانيات لا محدودة.", heroSubtitle: "من الحفر حتى إدارة الممتلكات، تغطي FCC كل مرحلة من مراحل البيئة المبنية تحت علامة تجارية متكاملة.", divisionLabel: "قسم", ctaTitle1: "هل تحتاج حزمة", ctaTitle2: "خدمات مخصصة؟", ctaSubtitle: "نصمّم خدماتنا وفق متطلبات مشروعك وميزانيتك. تحدّث مع فريقنا اليوم.", divisionNames: ["البناء والهندسة", "العقارات والممتلكات", "إدارة المرافق والممتلكات", "التصميم الداخلي والتشطيب", "القوى العاملة والمعدات"] },
    projects: { heroBadge: "معرض أعمالنا", heroTitle1: "أكثر من 500 مشروع.", heroTitle2: "بلا تنازلات.", heroSubtitle: "من المجمعات السكنية إلى البنية التحتية الوطنية — كل مشروع يمثّل التزامنا بالتميز والابتكار والتسليم في الوقت المحدد.", filterAll: "الكل", enquire: "استفسر", ctaTitle1: "يمكن أن يكون مشروعك", ctaTitle2: "تحفتنا القادمة", ctaSubtitle: "لنناقش رؤيتك ونحوّلها إلى مشروع حائز على جوائز.", startProject: "ابدأ مشروعاً", statValue: "إجمالي قيمة العقود", statContract: "مشاريع منجزة", statStates: "ولايات مُغطَّاة", statDelivery: "معدل التسليم في الوقت المحدد" },
    properties: { heroBadge: "سوق العقارات", heroTitle1: "اعثر على", heroTitle2: "عقارك المثالي", heroSubtitle: "اشترِ أو استأجر أو استثمر في عقارات متميزة عبر أسرع مدن نيجيريا نمواً — إعلانات موثّقة، وكلاء موثوقون، معاملات سلسة.", searchPlaceholder: "ابحث بالموقع أو المجمع أو نوع العقار...", sortNewest: "ترتيب: الأحدث", sortLowHigh: "السعر: من الأدنى إلى الأعلى", sortHighLow: "السعر: من الأعلى إلى الأدنى", listingsAvailable: "إعلانات متاحة", saved: "محفوظ", bookInspection: "احجز معاينة", confirmBooking: "تأكيد الحجز", whyBadge: "لماذا FCC للعقارات", whyTitle1: "الطريقة الأكثر أماناً للشراء", whyTitle2: "العقارات في نيجيريا", propFor: "لـ", beds: "غرفة نوم", baths: "حمام", popular: "الأكثر شيوعاً" },
    careers: { heroBadge: "انضم إلى فريقنا", heroTitle1: "ابنِ مسيرتك المهنية.", heroTitle2: "ابنِ مستقبل أفريقيا.", heroSubtitle: "انضم إلى فريق من أكثر من 1,000 متخصص يُشكّلون البيئة المبنية في أفريقيا. توفّر FCC نمواً مهنياً وتعويضات تنافسية وفرص العمل في مشاريع بارزة.", openRolesBadge: "وظائف شاغرة", openRolesTitle: "الفرص الحالية", artisanBadge: "قاعدة بيانات الحرفيين", artisanTitle1: "هل أنت متخصص", artisanTitle2: "في مجال الحرف؟", artisanSubtitle: "انضم إلى أفضل قاعدة بيانات لقوى العمل في البناء بنيجيريا. تطابق مع المشاريع، اكسب المزيد، طوّر مسيرتك.", formBadge: "قدّم الآن", formTitle: "قدّم طلبك", tabJob: "طلب وظيفة", tabLabor: "تسجيل عمال", tabContractor: "تسجيل مقاول", submitApplication: "إرسال الطلب" },
    contact: { heroBadge: "تواصل معنا", heroTitle1: "لنبنِ", heroTitle2: "رؤيتك معاً", heroSubtitle: "هل أنت مستعد لبدء مشروع؟ تبحث عن عقار استثماري؟ تحتاج حلاً للقوى العاملة؟ فريقنا مستعد للرد خلال 24 ساعة.", sendMessage: "أرسل لنا رسالة", messageSent: "تم إرسال الرسالة!", thankYou: "شكراً لتواصلك معنا. سيرد فريقنا خلال 24 ساعة.", sendAnother: "إرسال رسالة أخرى", fullName: "الاسم الكامل", emailAddress: "عنوان البريد الإلكتروني", phoneNumber: "رقم الهاتف", serviceRequired: "الخدمة المطلوبة", estimatedBudget: "الميزانية التقديرية", projectDescription: "وصف المشروع", projectDescPlaceholder: "أخبرنا عن مشروعك وجدوله الزمني وموقعه وأي متطلبات محددة...", directContacts: "جهات الاتصال المباشرة", responseTime: "أوقات الاستجابة", generalEnquiries: "الاستفسارات العامة", projectQuotations: "عروض أسعار المشاريع", emergencySupport: "دعم طوارئ الموقع", siteEmergency: "طوارئ في الموقع؟", siteEmergencyDesc: "اتصل بخط الطوارئ 24/7 للحالات العاجلة في الموقع.", officesBadge: "مكاتبنا", officesTitle1: "اعثر علينا", officesTitle2: "عبر نيجيريا" },
    footer: { tagline: "شركة واحدة. إمكانيات لا محدودة. نبني المدن ونصنع المستقبل عبر أفريقيا." },
  },

  /* ═══════════════ SPANISH ═══════════════ */
  es: {
    nav: { home: "Inicio", about: "Nosotros", services: "Servicios", projects: "Proyectos", properties: "Propiedades", careers: "Empleos", team: "Nuestro Equipo", contact: "Contacto", getQuote: "Obtener Cotización" },
    common: { learnMore: "Saber Más", contactUs: "Contáctenos", viewAll: "Ver Todo", startProject: "Iniciar Proyecto", getQuote: "Obtener Cotización", viewProjects: "Ver Nuestros Proyectos", readMore: "Leer Más", submit: "Enviar", calculate: "Calcular Estimado", reset: "Restablecer", search: "Buscar", filters: "Filtros", bookInspection: "Reservar Inspección", applyNow: "Aplicar Ahora", sendMessage: "Enviar Mensaje", allRightsReserved: "Todos los derechos reservados.", buildingCities: "Construyendo Ciudades. Creando Futuros.", privacyPolicy: "Política de Privacidad", termsOfService: "Términos de Servicio", emergencyLine: "Línea de Emergencia", ourDivisions: "Nuestras Divisiones", quickLinks: "Enlaces Rápidos" },
    home: { heroBadge: "Construyendo Ciudades. Creando Futuros.", heroH1a: "La Principal Potencia", heroH1b: "Constructora", heroH1c: "de África", heroSubtitle: "FCC Fore-City Construction ofrece soluciones de construcción, bienes raíces e inmobiliaria integrada de clase mundial — desde los cimientos hasta el acabado, en las ciudades de más rápido crecimiento de África.", heroFindProperty: "Buscar Propiedad", statProjects: "Proyectos Completados", statWorkforce: "Mano de Obra Calificada", statClients: "Clientes Satisfechos", statProperties: "Propiedades Entregadas", servicesBadge: "Lo Que Hacemos", servicesTitle1: "Cinco Divisiones Poderosas.", servicesTitle2: "Una Sola Empresa.", servicesSubtitle: "Desde el primer golpe de pala hasta la entrega de llaves, brindamos soluciones completas bajo un mismo techo.", whyBadge: "Por Qué Elegir FCC", whyTitle1: "La Confianza de las Grandes", whyTitle2: "Marcas de Nigeria", whyBody: "En más de 15 años, hemos construido un legado de confianza, calidad y entrega puntual. Nuestro enfoque integrado significa menos contratistas, finalización más rápida y mejores resultados.", portfolioBadge: "Portafolio", portfolioTitle: "Proyectos Destacados", featuredProjects: "Todos los Proyectos", testimonialsBadge: "Testimonios", testimonialsTitle: "Lo Que Dicen Nuestros Clientes", ctaTitle1: "¿Listo para Construir", ctaTitle2: "Algo Extraordinario?", ctaSubtitle: "Desde la primera consulta hasta la entrega del proyecto, FCC está con usted en cada paso.", ctaAbout: "Sobre FCC", trustedBy: "La Confianza de Líderes del Sector" },
    about: { heroBadge: "Nuestra Historia", heroTitle1: "Construyendo África,", heroTitle2: "Un Proyecto a la Vez", heroSubtitle: "FCC es la empresa de entorno construido más integrada de Nigeria — ofreciendo construcción, bienes raíces, gestión de propiedades, diseño de interiores y soluciones de fuerza laboral.", missionLabel: "Nuestra Misión", visionLabel: "Nuestra Visión", valuesBadge: "Nuestros Valores", valuesTitle1: "Lo Que Nos Impulsa", valuesTitle2: "Cada Día", certBadge: "Acreditaciones", certTitle1: "Certificado &", certTitle2: "Acreditado Internacionalmente", certSubtitle: "Nuestras certificaciones no son solo insignias — son prueba de nuestro compromiso con los estándares internacionales de calidad y seguridad.", workforceBadge: "Nuestra Fuerza Laboral", workforceTitle1: "Más de 1,000 Profesionales.", workforceTitle2: "Un Equipo Imparable.", timelineBadge: "Nuestro Recorrido", timelineTitle1: "15 Años de", timelineTitle2: "Excelencia Constructora", leadershipBadge: "Liderazgo", leadershipTitle: "Conoce al Equipo", ctaTitle1: "Construyamos Algo", ctaTitle2: "Grande Juntos", ctaSubtitle: "Ya sea que esté iniciando un nuevo proyecto o buscando invertir en bienes raíces, FCC está listo." },
    services: { heroBadge: "Nuestros Servicios", heroTitle1: "Cinco Divisiones.", heroTitle2: "Posibilidades Ilimitadas.", heroSubtitle: "Desde el inicio hasta la gestión de propiedades, FCC cubre cada etapa del ciclo del entorno construido bajo una marca integrada.", divisionLabel: "División", ctaTitle1: "¿Necesita un Paquete", ctaTitle2: "de Servicios Personalizado?", ctaSubtitle: "Adaptamos nuestros servicios a sus requisitos y presupuesto específicos. Hable con nuestro equipo hoy.", divisionNames: ["Construcción e Ingeniería", "Bienes Raíces y Propiedad", "Gestión de Instalaciones", "Diseño de Interiores y Acabados", "Fuerza Laboral y Equipos"] },
    projects: { heroBadge: "Nuestro Portafolio", heroTitle1: "500+ Proyectos.", heroTitle2: "Cero Compromisos.", heroSubtitle: "Desde urbanizaciones residenciales hasta infraestructura nacional — cada proyecto representa un compromiso con la excelencia, la innovación y la entrega puntual.", filterAll: "Todos", enquire: "Consultar", ctaTitle1: "Su Proyecto Podría Ser", ctaTitle2: "Nuestra Próxima Obra Maestra", ctaSubtitle: "Hablemos de su visión y conviértala en un proyecto premiado.", startProject: "Iniciar Proyecto", statValue: "Valor Total de Contratos", statContract: "Proyectos Completados", statStates: "Estados Cubiertos", statDelivery: "Tasa de Entrega a Tiempo" },
    properties: { heroBadge: "Mercado Inmobiliario", heroTitle1: "Encuentra Tu", heroTitle2: "Propiedad Ideal", heroSubtitle: "Compra, alquila o invierte en propiedades premium en las ciudades de más rápido crecimiento de Nigeria — listados verificados, agentes de confianza, transacciones fluidas.", searchPlaceholder: "Buscar por ubicación, urbanización o tipo de propiedad...", sortNewest: "Ordenar: Más Reciente", sortLowHigh: "Precio: Menor a Mayor", sortHighLow: "Precio: Mayor a Menor", listingsAvailable: "Listados Disponibles", saved: "guardados", bookInspection: "Reservar Inspección", confirmBooking: "Confirmar Reserva", whyBadge: "Por Qué FCC Propiedades", whyTitle1: "La Forma Más Segura de Comprar", whyTitle2: "Propiedad en Nigeria", propFor: "Para", beds: "Hab", baths: "Baño", popular: "Popular" },
    careers: { heroBadge: "Únete a Nuestro Equipo", heroTitle1: "Construye Tu Carrera.", heroTitle2: "Construye el Futuro de África.", heroSubtitle: "Únete a un equipo de 1,000+ profesionales que dan forma al entorno construido de África. FCC ofrece crecimiento profesional, compensación competitiva y la oportunidad de trabajar en proyectos emblemáticos.", openRolesBadge: "Vacantes", openRolesTitle: "Oportunidades Actuales", artisanBadge: "Base de Datos de Artesanos", artisanTitle1: "¿Eres un Profesional", artisanTitle2: "del Oficio?", artisanSubtitle: "Únete a la principal base de datos de fuerza laboral de construcción de Nigeria. Encuentra proyectos, gana más y construye tu carrera.", formBadge: "Aplicar Ahora", formTitle: "Envía Tu Solicitud", tabJob: "Solicitud de Empleo", tabLabor: "Registro de Mano de Obra", tabContractor: "Registro de Contratista", submitApplication: "Enviar Solicitud" },
    contact: { heroBadge: "Ponte en Contacto", heroTitle1: "Construyamos", heroTitle2: "Tu Visión Juntos", heroSubtitle: "¿Listo para iniciar un proyecto? ¿Buscas una propiedad de inversión? ¿Necesitas una solución de fuerza laboral? Nuestro equipo responderá en 24 horas.", sendMessage: "Envíenos un Mensaje", messageSent: "¡Mensaje Enviado!", thankYou: "Gracias por contactarnos. Nuestro equipo responderá dentro de 24 horas.", sendAnother: "Enviar Otro Mensaje", fullName: "Nombre Completo", emailAddress: "Correo Electrónico", phoneNumber: "Número de Teléfono", serviceRequired: "Servicio Requerido", estimatedBudget: "Presupuesto Estimado", projectDescription: "Descripción del Proyecto", projectDescPlaceholder: "Cuéntenos sobre su proyecto, plazos, ubicación y cualquier requisito específico...", directContacts: "Contactos Directos", responseTime: "Tiempos de Respuesta", generalEnquiries: "Consultas Generales", projectQuotations: "Cotizaciones de Proyectos", emergencySupport: "Emergencia en Obra", siteEmergency: "¿Emergencia en Obra?", siteEmergencyDesc: "Llame a nuestra línea de emergencia 24/7 para situaciones urgentes en obra.", officesBadge: "Nuestras Oficinas", officesTitle1: "Encuéntrenos", officesTitle2: "en Nigeria" },
    footer: { tagline: "Una empresa. Posibilidades infinitas. Construyendo ciudades y creando futuros en toda África." },
  },

  /* ═══════════════ PORTUGUESE ═══════════════ */
  pt: {
    nav: { home: "Início", about: "Sobre Nós", services: "Serviços", projects: "Projetos", properties: "Imóveis", careers: "Carreiras", team: "Nossa Equipe", contact: "Contato", getQuote: "Obter Orçamento" },
    common: { learnMore: "Saiba Mais", contactUs: "Fale Conosco", viewAll: "Ver Tudo", startProject: "Iniciar Projeto", getQuote: "Obter Orçamento", viewProjects: "Ver Nossos Projetos", readMore: "Ler Mais", submit: "Enviar", calculate: "Calcular Estimativa", reset: "Redefinir", search: "Pesquisar", filters: "Filtros", bookInspection: "Agendar Visita", applyNow: "Candidatar-se", sendMessage: "Enviar Mensagem", allRightsReserved: "Todos os direitos reservados.", buildingCities: "Construindo Cidades. Criando Futuros.", privacyPolicy: "Política de Privacidade", termsOfService: "Termos de Serviço", emergencyLine: "Linha de Emergência", ourDivisions: "Nossas Divisões", quickLinks: "Links Rápidos" },
    home: { heroBadge: "Construindo Cidades. Criando Futuros.", heroH1a: "A Principal Potência", heroH1b: "de Construção", heroH1c: "da África", heroSubtitle: "FCC Fore-City Construction entrega construção de classe mundial, imóveis e soluções integradas de propriedade — da fundação ao acabamento, nas cidades de crescimento mais rápido da África.", heroFindProperty: "Encontrar Imóvel", statProjects: "Projetos Concluídos", statWorkforce: "Mão de Obra Qualificada", statClients: "Clientes Satisfeitos", statProperties: "Imóveis Entregues", servicesBadge: "O Que Fazemos", servicesTitle1: "Cinco Divisões Poderosas.", servicesTitle2: "Uma Empresa.", servicesSubtitle: "Do primeiro golpe de picareta até a entrega das chaves, oferecemos soluções completas sob um mesmo teto.", whyBadge: "Por Que Escolher FCC", whyTitle1: "A Confiança das Maiores", whyTitle2: "Marcas da Nigéria", whyBody: "Em mais de 15 anos, construímos um legado de confiança, qualidade e entrega no prazo. Nossa abordagem integrada significa menos empreiteiros, conclusão mais rápida e melhores resultados.", portfolioBadge: "Portfólio", portfolioTitle: "Projetos em Destaque", featuredProjects: "Todos os Projetos", testimonialsBadge: "Depoimentos", testimonialsTitle: "O Que Nossos Clientes Dizem", ctaTitle1: "Pronto para Construir", ctaTitle2: "Algo Extraordinário?", ctaSubtitle: "Da primeira consulta à entrega do projeto, a FCC está com você em cada etapa.", ctaAbout: "Sobre a FCC", trustedBy: "A Confiança dos Líderes do Setor" },
    about: { heroBadge: "Nossa História", heroTitle1: "Construindo a África,", heroTitle2: "Um Projeto de Cada Vez", heroSubtitle: "FCC é a empresa de ambiente construído mais integrada da Nigéria — oferecendo construção, imóveis, gestão de propriedades, design de interiores e soluções de mão de obra.", missionLabel: "Nossa Missão", visionLabel: "Nossa Visão", valuesBadge: "Nossos Valores", valuesTitle1: "O Que Nos Motiva", valuesTitle2: "Todos os Dias", certBadge: "Acreditações", certTitle1: "Certificado &", certTitle2: "Acreditado Internacionalmente", certSubtitle: "Nossas certificações não são apenas emblemas — são prova do nosso compromisso com padrões internacionais de qualidade e segurança.", workforceBadge: "Nossa Força de Trabalho", workforceTitle1: "1.000+ Profissionais.", workforceTitle2: "Uma Equipe Imparável.", timelineBadge: "Nossa Jornada", timelineTitle1: "15 Anos de", timelineTitle2: "Excelência em Construção", leadershipBadge: "Liderança", leadershipTitle: "Conheça a Equipe", ctaTitle1: "Vamos Construir Algo", ctaTitle2: "Grande Juntos", ctaSubtitle: "Seja iniciando um novo projeto ou buscando investir em imóveis, a FCC está pronta." },
    services: { heroBadge: "Nossos Serviços", heroTitle1: "Cinco Divisões.", heroTitle2: "Possibilidades Ilimitadas.", heroSubtitle: "Da escavação à gestão de propriedades, a FCC cobre cada etapa do ciclo do ambiente construído sob uma marca integrada.", divisionLabel: "Divisão", ctaTitle1: "Precisa de um Pacote", ctaTitle2: "de Serviços Personalizado?", ctaSubtitle: "Adaptamos nossos serviços aos seus requisitos e orçamento específicos. Fale com nossa equipe hoje.", divisionNames: ["Construção e Engenharia", "Imóveis e Propriedades", "Gestão de Instalações", "Design de Interiores e Acabamento", "Força de Trabalho e Equipamentos"] },
    projects: { heroBadge: "Nosso Portfólio", heroTitle1: "500+ Projetos.", heroTitle2: "Zero Compromissos.", heroSubtitle: "De condomínios residenciais a infraestrutura nacional — cada projeto representa um compromisso com excelência, inovação e entrega no prazo.", filterAll: "Todos", enquire: "Consultar", ctaTitle1: "Seu Projeto Pode Ser", ctaTitle2: "Nossa Próxima Obra Prima", ctaSubtitle: "Vamos discutir sua visão e transformá-la em um projeto premiado.", startProject: "Iniciar Projeto", statValue: "Valor Total de Contratos", statContract: "Projetos Concluídos", statStates: "Estados Cobertos", statDelivery: "Taxa de Entrega no Prazo" },
    properties: { heroBadge: "Mercado Imobiliário", heroTitle1: "Encontre Seu", heroTitle2: "Imóvel Perfeito", heroSubtitle: "Compre, alugue ou invista em imóveis premium nas cidades de crescimento mais rápido da Nigéria — listagens verificadas, corretores confiáveis, transações tranquilas.", searchPlaceholder: "Pesquisar por localização, condomínio ou tipo de imóvel...", sortNewest: "Ordenar: Mais Recente", sortLowHigh: "Preço: Menor para Maior", sortHighLow: "Preço: Maior para Menor", listingsAvailable: "Listagens Disponíveis", saved: "salvos", bookInspection: "Agendar Visita", confirmBooking: "Confirmar Agendamento", whyBadge: "Por Que FCC Imóveis", whyTitle1: "A Forma Mais Segura de Comprar", whyTitle2: "Imóveis na Nigéria", propFor: "Para", beds: "Quarto", baths: "Banheiro", popular: "Popular" },
    careers: { heroBadge: "Junte-se à Nossa Equipe", heroTitle1: "Construa Sua Carreira.", heroTitle2: "Construa o Futuro da África.", heroSubtitle: "Junte-se a uma equipe de 1.000+ profissionais moldando o ambiente construído africano. A FCC oferece crescimento de carreira, remuneração competitiva e oportunidades em projetos emblemáticos.", openRolesBadge: "Vagas Abertas", openRolesTitle: "Oportunidades Atuais", artisanBadge: "Base de Dados de Artesãos", artisanTitle1: "Você é um Profissional", artisanTitle2: "de Ofício Qualificado?", artisanSubtitle: "Junte-se à principal base de dados de força de trabalho de construção da Nigéria. Encontre projetos, ganhe mais e construa sua carreira.", formBadge: "Candidatar-se Agora", formTitle: "Envie Sua Candidatura", tabJob: "Candidatura a Emprego", tabLabor: "Registro de Mão de Obra", tabContractor: "Registro de Empreiteiro", submitApplication: "Enviar Candidatura" },
    contact: { heroBadge: "Entre em Contato", heroTitle1: "Vamos Construir", heroTitle2: "Sua Visão Juntos", heroSubtitle: "Pronto para iniciar um projeto? Procurando um imóvel de investimento? Precisa de uma solução de mão de obra? Nossa equipe responderá em 24 horas.", sendMessage: "Envie-nos uma Mensagem", messageSent: "Mensagem Enviada!", thankYou: "Obrigado por entrar em contato. Nossa equipe responderá em 24 horas.", sendAnother: "Enviar Outra Mensagem", fullName: "Nome Completo", emailAddress: "Endereço de E-mail", phoneNumber: "Número de Telefone", serviceRequired: "Serviço Necessário", estimatedBudget: "Orçamento Estimado", projectDescription: "Descrição do Projeto", projectDescPlaceholder: "Conte-nos sobre seu projeto, cronograma, localização e quaisquer requisitos específicos...", directContacts: "Contatos Diretos", responseTime: "Tempos de Resposta", generalEnquiries: "Consultas Gerais", projectQuotations: "Cotações de Projetos", emergencySupport: "Emergência no Canteiro", siteEmergency: "Emergência no Canteiro?", siteEmergencyDesc: "Ligue para nossa linha de emergência 24/7 para situações urgentes no canteiro.", officesBadge: "Nossos Escritórios", officesTitle1: "Encontre-nos", officesTitle2: "na Nigéria" },
    footer: { tagline: "Uma empresa. Possibilidades infinitas. Construindo cidades e criando futuros por toda a África." },
  },

  /* ═══════════════ GERMAN ═══════════════ */
  de: {
    nav: { home: "Startseite", about: "Über Uns", services: "Leistungen", projects: "Projekte", properties: "Immobilien", careers: "Karriere", team: "Unser Team", contact: "Kontakt", getQuote: "Angebot Erhalten" },
    common: { learnMore: "Mehr Erfahren", contactUs: "Kontakt Aufnehmen", viewAll: "Alle Anzeigen", startProject: "Projekt Starten", getQuote: "Angebot Erhalten", viewProjects: "Unsere Projekte", readMore: "Weiterlesen", submit: "Absenden", calculate: "Schätzen", reset: "Zurücksetzen", search: "Suchen", filters: "Filter", bookInspection: "Besichtigung Buchen", applyNow: "Jetzt Bewerben", sendMessage: "Nachricht Senden", allRightsReserved: "Alle Rechte vorbehalten.", buildingCities: "Städte Bauen. Zukunft Gestalten.", privacyPolicy: "Datenschutzrichtlinie", termsOfService: "Nutzungsbedingungen", emergencyLine: "Notfallleitung", ourDivisions: "Unsere Abteilungen", quickLinks: "Schnelllinks" },
    home: { heroBadge: "Städte Bauen. Zukunft Gestalten.", heroH1a: "Afrikas Führende", heroH1b: "Bau-", heroH1c: "Kraft", heroSubtitle: "FCC Fore-City Construction bietet weltstandardsgerechte Bau-, Immobilien- und integrierte Immobilienlösungen — vom Fundament bis zur Fertigstellung, in Afrikas am schnellsten wachsenden Städten.", heroFindProperty: "Immobilie Finden", statProjects: "Abgeschlossene Projekte", statWorkforce: "Qualifizierte Fachkräfte", statClients: "Zufriedene Kunden", statProperties: "Übergebene Immobilien", servicesBadge: "Was Wir Tun", servicesTitle1: "Fünf Starke Abteilungen.", servicesTitle2: "Ein Unternehmen.", servicesSubtitle: "Vom Spatenstich bis zur Schlüsselübergabe bieten wir ganzheitliche Lösungen für die Bauumgebung unter einem Dach.", whyBadge: "Warum FCC Wählen", whyTitle1: "Vertraut von Nigerias", whyTitle2: "Größten Marken", whyBody: "In über 15 Jahren haben wir ein Erbe aus Vertrauen, Qualität und termingerechter Lieferung aufgebaut. Unser integrierter Ansatz bedeutet weniger Auftragnehmer, schnellere Fertigstellung und bessere Ergebnisse.", portfolioBadge: "Portfolio", portfolioTitle: "Ausgewählte Projekte", featuredProjects: "Alle Projekte", testimonialsBadge: "Referenzen", testimonialsTitle: "Was Unsere Kunden Sagen", ctaTitle1: "Bereit, Etwas", ctaTitle2: "Außergewöhnliches zu Bauen?", ctaSubtitle: "Von der ersten Beratung bis zur Projektübergabe ist FCC bei jedem Schritt an Ihrer Seite.", ctaAbout: "Über FCC", trustedBy: "Vertraut von Branchenführern" },
    about: { heroBadge: "Unsere Geschichte", heroTitle1: "Afrika Bauen,", heroTitle2: "Ein Projekt nach dem Anderen", heroSubtitle: "FCC ist das am stärksten integrierte Unternehmen für gebaute Umgebung in Nigeria — bietet Bau, Immobilien, Immobilienverwaltung, Innenarchitektur und Personaldienstleistungen.", missionLabel: "Unsere Mission", visionLabel: "Unsere Vision", valuesBadge: "Unsere Werte", valuesTitle1: "Was Uns Antreibt", valuesTitle2: "Jeden Tag", certBadge: "Akkreditierungen", certTitle1: "Zertifiziert &", certTitle2: "International Anerkannt", certSubtitle: "Unsere Zertifizierungen sind nicht nur Abzeichen — sie sind Beweis unseres Engagements für internationale Qualitäts- und Sicherheitsstandards.", workforceBadge: "Unsere Belegschaft", workforceTitle1: "1.000+ Fachleute.", workforceTitle2: "Ein Unaufhaltsames Team.", timelineBadge: "Unser Weg", timelineTitle1: "15 Jahre", timelineTitle2: "Bauexzellenz", leadershipBadge: "Führung", leadershipTitle: "Das Team Kennenlernen", ctaTitle1: "Lass Uns Gemeinsam", ctaTitle2: "Großes Schaffen", ctaSubtitle: "Ob Sie ein neues Projekt starten oder in Immobilien investieren möchten, FCC ist bereit." },
    services: { heroBadge: "Unsere Leistungen", heroTitle1: "Fünf Abteilungen.", heroTitle2: "Unbegrenzte Möglichkeiten.", heroSubtitle: "Vom Baubeginn bis zur Immobilienverwaltung deckt FCC jede Phase des Bauzyklus unter einer integrierten Marke ab.", divisionLabel: "Abteilung", ctaTitle1: "Maßgeschneidertes", ctaTitle2: "Dienstleistungspaket?", ctaSubtitle: "Wir passen unsere Dienstleistungen an Ihre spezifischen Projektanforderungen und Ihr Budget an. Sprechen Sie heute mit unserem Team.", divisionNames: ["Bau & Ingenieurwesen", "Immobilien & Eigentum", "Facility & Immobilienverwaltung", "Innenarchitektur & Ausbau", "Personal & Gerätelösungen"] },
    projects: { heroBadge: "Unser Portfolio", heroTitle1: "500+ Projekte.", heroTitle2: "Keine Kompromisse.", heroSubtitle: "Von Wohnanlagen bis hin zu nationaler Infrastruktur — jedes Projekt steht für unser Engagement für Exzellenz, Innovation und termingerechte Lieferung.", filterAll: "Alle", enquire: "Anfragen", ctaTitle1: "Ihr Projekt Könnte", ctaTitle2: "Unser Nächstes Meisterwerk Sein", ctaSubtitle: "Lassen Sie uns Ihre Vision besprechen und sie in ein preisgekröntes Projekt verwandeln.", startProject: "Projekt Starten", statValue: "Gesamter Vertragswert", statContract: "Abgeschlossene Projekte", statStates: "Abgedeckte Bundesstaaten", statDelivery: "Termingerechte Lieferrate" },
    properties: { heroBadge: "Immobilienmarkt", heroTitle1: "Finden Sie Ihre", heroTitle2: "Traumimmobilie", heroSubtitle: "Kaufen, mieten oder investieren Sie in erstklassige Immobilien in Nigerias am schnellsten wachsenden Städten — verifizierte Angebote, vertrauenswürdige Makler, reibungslose Transaktionen.", searchPlaceholder: "Nach Standort, Anlage oder Immobilientyp suchen...", sortNewest: "Sortieren: Neueste", sortLowHigh: "Preis: Aufsteigend", sortHighLow: "Preis: Absteigend", listingsAvailable: "Angebote Verfügbar", saved: "gespeichert", bookInspection: "Besichtigung Buchen", confirmBooking: "Buchung Bestätigen", whyBadge: "Warum FCC Immobilien", whyTitle1: "Der Sicherste Weg, Immobilien", whyTitle2: "in Nigeria zu Kaufen", propFor: "Für", beds: "Schlafzimmer", baths: "Badezimmer", popular: "Beliebt" },
    careers: { heroBadge: "Treten Sie Unserem Team Bei", heroTitle1: "Bauen Sie Ihre Karriere.", heroTitle2: "Bauen Sie Afrikas Zukunft.", heroSubtitle: "Treten Sie einem Team von 1.000+ Fachleuten bei, die Afrikas gebaute Umgebung gestalten. FCC bietet Karrierewachstum, wettbewerbsfähige Vergütung und die Möglichkeit, an Wahrzeichen-Projekten zu arbeiten.", openRolesBadge: "Offene Stellen", openRolesTitle: "Aktuelle Möglichkeiten", artisanBadge: "Handwerkerdatenbank", artisanTitle1: "Sind Sie ein Qualifizierter", artisanTitle2: "Handwerker?", artisanSubtitle: "Treten Sie der führenden Bau-Arbeitskräftedatenbank Nigerias bei. Werden Sie mit Projekten gematcht, verdienen Sie mehr und bauen Sie Ihre Karriere auf.", formBadge: "Jetzt Bewerben", formTitle: "Bewerbung Einreichen", tabJob: "Stellenbewerbung", tabLabor: "Arbeitskräfteregistrierung", tabContractor: "Auftragnehmerregistrierung", submitApplication: "Bewerbung Einreichen" },
    contact: { heroBadge: "Kontakt Aufnehmen", heroTitle1: "Lassen Sie Uns Gemeinsam", heroTitle2: "Ihre Vision Bauen", heroSubtitle: "Bereit, ein Projekt zu starten? Suchen Sie eine Anlageimmobilie? Brauchen Sie eine Personallösung? Unser Team antwortet innerhalb von 24 Stunden.", sendMessage: "Senden Sie Uns eine Nachricht", messageSent: "Nachricht Gesendet!", thankYou: "Vielen Dank für Ihre Kontaktaufnahme. Unser Team wird innerhalb von 24 Stunden antworten.", sendAnother: "Weitere Nachricht Senden", fullName: "Vollständiger Name", emailAddress: "E-Mail-Adresse", phoneNumber: "Telefonnummer", serviceRequired: "Benötigte Leistung", estimatedBudget: "Geschätztes Budget", projectDescription: "Projektbeschreibung", projectDescPlaceholder: "Erzählen Sie uns von Ihrem Projekt, Zeitplan, Standort und spezifischen Anforderungen...", directContacts: "Direktkontakte", responseTime: "Antwortzeiten", generalEnquiries: "Allgemeine Anfragen", projectQuotations: "Projektangebote", emergencySupport: "Baustellennotfall", siteEmergency: "Baustellennotfall?", siteEmergencyDesc: "Rufen Sie unsere 24/7-Notfallleitung für dringende Baustellensituationen an.", officesBadge: "Unsere Büros", officesTitle1: "Finden Sie Uns", officesTitle2: "in Nigeria" },
    footer: { tagline: "Ein Unternehmen. Grenzenlose Möglichkeiten. Städte bauen und Zukunft gestalten in ganz Afrika." },
  },

  /* ═══════════════ SWAHILI ═══════════════ */
  sw: {
    nav: { home: "Nyumbani", about: "Kuhusu Sisi", services: "Huduma", projects: "Miradi", properties: "Mali", careers: "Kazi", team: "Timu Yetu", contact: "Wasiliana Nasi", getQuote: "Pata Nukuu" },
    common: { learnMore: "Jifunze Zaidi", contactUs: "Wasiliana Nasi", viewAll: "Tazama Yote", startProject: "Anza Mradi Wako", getQuote: "Pata Nukuu", viewProjects: "Tazama Miradi Yetu", readMore: "Soma Zaidi", submit: "Wasilisha", calculate: "Hesabu Makadirio", reset: "Weka Upya", search: "Tafuta", filters: "Vichujio", bookInspection: "Weka Ukaguzi", applyNow: "Omba Sasa", sendMessage: "Tuma Ujumbe", allRightsReserved: "Haki zote zimehifadhiwa.", buildingCities: "Kujenga Miji. Kuunda Mustakabali.", privacyPolicy: "Sera ya Faragha", termsOfService: "Masharti ya Huduma", emergencyLine: "Simu ya Dharura", ourDivisions: "Idara Zetu", quickLinks: "Viungo vya Haraka" },
    home: { heroBadge: "Kujenga Miji. Kuunda Mustakabali.", heroH1a: "Nguvu Kuu ya", heroH1b: "Ujenzi", heroH1c: "Barani Afrika", heroSubtitle: "FCC Fore-City Construction inatoa ujenzi wa kiwango cha ulimwengu, mali isiyohamishika, na suluhu za mali zilizounganishwa — kutoka msingi hadi ukamilishaji, katika miji inayokua kwa haraka zaidi barani Afrika.", heroFindProperty: "Tafuta Mali", statProjects: "Miradi Iliyokamilika", statWorkforce: "Wafanyakazi Wenye Ujuzi", statClients: "Wateja Wafurahi", statProperties: "Mali Zilizotolewa", servicesBadge: "Tunachofanya", servicesTitle1: "Idara Tano Zenye Nguvu.", servicesTitle2: "Kampuni Moja.", servicesSubtitle: "Kuanzia kuvunja ardhi hadi kutoa funguo, tunatoa suluhu kamili za mazingira ya ujenzi chini ya paa moja.", whyBadge: "Kwa Nini Chagua FCC", whyTitle1: "Kuaminiwa na Biashara", whyTitle2: "Kubwa za Nigeria", whyBody: "Kwa miaka 15+, tumejenga urithi wa uaminifu, ubora, na utoaji kwa wakati. Mbinu yetu iliyounganishwa inamaanisha makandarasi wachache, ukamilishaji wa haraka, na matokeo bora.", portfolioBadge: "Kazi Zetu", portfolioTitle: "Miradi Maarufu", featuredProjects: "Miradi Yote", testimonialsBadge: "Ushuhuda", testimonialsTitle: "Wateja Wetu Wanasema Nini", ctaTitle1: "Uko Tayari Kujenga", ctaTitle2: "Kitu Cha Ajabu?", ctaSubtitle: "Kuanzia mashauriano ya kwanza hadi uwasilishaji wa mradi, FCC iko nawe kila hatua.", ctaAbout: "Kuhusu FCC", trustedBy: "Kuaminiwa na Viongozi wa Sekta" },
    about: { heroBadge: "Hadithi Yetu", heroTitle1: "Kujenga Afrika,", heroTitle2: "Mradi Mmoja kwa Wakati", heroSubtitle: "FCC ni kampuni ya mazingira ya ujenzi iliyounganishwa zaidi nchini Nigeria — ikitoa ujenzi, mali isiyohamishika, usimamizi wa mali, ubunifu wa mambo ya ndani, na suluhu za nguvu kazi.", missionLabel: "Dhamira Yetu", visionLabel: "Maono Yetu", valuesBadge: "Maadili Yetu", valuesTitle1: "Kinachoutuchochea", valuesTitle2: "Kila Siku", certBadge: "Vyeti", certTitle1: "Imeidhinishwa &", certTitle2: "Inatambuliwa Kimataifa", certSubtitle: "Vyeti vyetu si alama tu — ni ushahidi wa kujitolea kwetu kwa viwango vya kimataifa vya ubora na usalama.", workforceBadge: "Nguvu Kazi Yetu", workforceTitle1: "Wataalamu 1,000+.", workforceTitle2: "Timu Moja Isiyoweza Kusimamishwa.", timelineBadge: "Safari Yetu", timelineTitle1: "Miaka 15 ya", timelineTitle2: "Ubora wa Ujenzi", leadershipBadge: "Uongozi", leadershipTitle: "Kutana na Timu", ctaTitle1: "Tuunde Kitu", ctaTitle2: "Kikubwa Pamoja", ctaSubtitle: "Iwe unaanza mradi mpya au unatafuta kuwekeza katika mali isiyohamishika, FCC iko tayari." },
    services: { heroBadge: "Huduma Zetu", heroTitle1: "Idara Tano.", heroTitle2: "Uwezekano Usio na Mipaka.", heroSubtitle: "Kuanzia kuvunja ardhi hadi usimamizi wa mali, FCC inashughulikia kila hatua ya mzunguko wa mazingira ya ujenzi chini ya chapa iliyounganishwa.", divisionLabel: "Idara", ctaTitle1: "Unahitaji Mfuko", ctaTitle2: "Maalum wa Huduma?", ctaSubtitle: "Tunabuni huduma zetu kulingana na mahitaji yako maalum ya mradi na bajeti. Zungumza na timu yetu leo.", divisionNames: ["Ujenzi & Uhandisi", "Mali Isiyohamishika", "Usimamizi wa Vifaa & Mali", "Ubunifu wa Mambo ya Ndani & Ukamilishaji", "Nguvu Kazi & Vifaa"] },
    projects: { heroBadge: "Kazi Zetu", heroTitle1: "Miradi 500+.", heroTitle2: "Bila Makubaliano Mabaya.", heroSubtitle: "Kutoka makazi ya kifahari hadi miundombinu ya kitaifa — kila mradi unawakilisha kujitolea kwa ubora, ubunifu, na utoaji kwa wakati.", filterAll: "Yote", enquire: "Uliza", ctaTitle1: "Mradi Wako Unaweza Kuwa", ctaTitle2: "Kazi Yetu Inayofuata", ctaSubtitle: "Tuzungumze kuhusu maono yako na tuyabadilishe kuwa mradi uliopata tuzo.", startProject: "Anza Mradi", statValue: "Jumla ya Thamani ya Mikataba", statContract: "Miradi Iliyokamilika", statStates: "Majimbo Yaliyofunikwa", statDelivery: "Kiwango cha Utoaji kwa Wakati" },
    properties: { heroBadge: "Soko la Mali", heroTitle1: "Pata Mali", heroTitle2: "Yako Bora", heroSubtitle: "Nunua, kodi, au wekeza katika mali za kifahari katika miji inayokua kwa haraka zaidi nchini Nigeria — orodha zilizothibitishwa, mawakala wa kuaminiwa, miamala rahisi.", searchPlaceholder: "Tafuta eneo, makazi, au aina ya mali...", sortNewest: "Panga: Mpya Zaidi", sortLowHigh: "Bei: Chini hadi Juu", sortHighLow: "Bei: Juu hadi Chini", listingsAvailable: "Orodha Zinapatikana", saved: "zilizohifadhiwa", bookInspection: "Weka Ukaguzi", confirmBooking: "Thibitisha Uhifadhi", whyBadge: "Kwa Nini Mali za FCC", whyTitle1: "Njia Salama Zaidi ya Kununua", whyTitle2: "Mali Nchini Nigeria", propFor: "Kwa", beds: "Chumba cha Kulala", baths: "Bafuni", popular: "Maarufu" },
    careers: { heroBadge: "Jiunge na Timu Yetu", heroTitle1: "Jenga Kazi Yako.", heroTitle2: "Jenga Mustakabali wa Afrika.", heroSubtitle: "Jiunge na timu ya wataalamu 1,000+ wanaobuni mazingira ya ujenzi barani Afrika. FCC inatoa ukuaji wa kazi, malipo ya ushindani, na fursa ya kufanya kazi katika miradi ya kimkakati.", openRolesBadge: "Nafasi Wazi", openRolesTitle: "Fursa za Sasa", artisanBadge: "Hifadhidata ya Mafundi", artisanTitle1: "Je, Wewe ni Mtaalamu", artisanTitle2: "wa Ufundi?", artisanSubtitle: "Jiunge na hifadhidata kuu ya nguvu kazi ya ujenzi nchini Nigeria. Oana na miradi, pata zaidi, na jenga kazi yako.", formBadge: "Omba Sasa", formTitle: "Wasilisha Ombi Lako", tabJob: "Ombi la Kazi", tabLabor: "Usajili wa Wafanyakazi", tabContractor: "Usajili wa Mkandarasi", submitApplication: "Wasilisha Ombi" },
    contact: { heroBadge: "Wasiliana Nasi", heroTitle1: "Tuunde", heroTitle2: "Maono Yako Pamoja", heroSubtitle: "Uko tayari kuanza mradi? Unatafuta mali ya uwekezaji? Unahitaji suluhu ya nguvu kazi? Timu yetu iko tayari kujibu ndani ya saa 24.", sendMessage: "Tutumie Ujumbe", messageSent: "Ujumbe Umetumwa!", thankYou: "Asante kwa kuwasiliana nasi. Timu yetu itajibu ndani ya saa 24.", sendAnother: "Tuma Ujumbe Mwingine", fullName: "Jina Kamili", emailAddress: "Anwani ya Barua pepe", phoneNumber: "Nambari ya Simu", serviceRequired: "Huduma Inayohitajika", estimatedBudget: "Bajeti ya Makadirio", projectDescription: "Maelezo ya Mradi", projectDescPlaceholder: "Tuambie kuhusu mradi wako, ratiba, mahali, na mahitaji yoyote maalum...", directContacts: "Mawasiliano ya Moja kwa Moja", responseTime: "Nyakati za Kujibu", generalEnquiries: "Maswali ya Jumla", projectQuotations: "Nukuu za Mradi", emergencySupport: "Dharura ya Tovuti", siteEmergency: "Dharura kwenye Tovuti?", siteEmergencyDesc: "Piga simu laini yetu ya dharura ya 24/7 kwa hali za haraka za tovuti.", officesBadge: "Ofisi Zetu", officesTitle1: "Tupate", officesTitle2: "Kote Nchini Nigeria" },
    footer: { tagline: "Kampuni moja. Uwezekano usio na mipaka. Kujenga miji na kuunda mustakabali kote barani Afrika." },
  },
};

export default t;
